### ISSUE TITLE
Editors for code changes

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#102]
Someone's editor is leaving trailing spaces when editing source files, which my editor ([Atom](https://atom.io/), which is awesome) trims by default.

To avoid PRs containing extra apparent changes involving whitespace, should we:
- ensure our editors to _always_ remove trailing whitespace
- have our editors _always_ ignore trailing whitespace

We're presumably already standardized on spaces instead of tabs!

**Comment by davidlmobley** [comment]
Ah, good point. I'll circulate amongst my group and we'll sort this out for the future. Thanks. Since you're manipulating `forcefield.py`, this was probably me, as I'm the only other one who has touched this. I'll figure out how to get my editor to remove those.

(FYI, @bannanc @camizanette @cbayly13)

**Comment by davidlmobley** [comment]
Oops, I missed that this was a question. I'd say "always remove", but I don't have strong preferences. Requests, @jchodera ?

**Comment by jchodera** [comment]
I'd prefer to always remove trailing whitespace, but the most important thing is to just be consistent.

**Comment by davidlmobley** [comment]
For now, let's agree to remove it, and I'll revisit this if for some reason our editors don't allow for that. Agreed that consistency is key.

**Comment by davidlmobley** [comment]
I've passed this on (and info on how to do so) to everyone in my lab. So I think we just need @mrshirts and @bmanubay to see it and then we can close this.

Summary points:
- Use four spaces for indentation in Python, not tabs
- Strip trailing whitespace
- (my addition) Make reasonable effort not to have code lines extend past 80 characters except when there is a good reason for it (high levels of indentation for example)

**Comment by bmanubay** [comment]
Noted!

**Comment by bannanc** [comment]
I updated my editor to correct for this, I realized I should maybe acknowledge on here as well.

**Comment by davidlmobley** [comment]
Marking as closed.
