### ISSUE TITLE
Support for bond charge corrections

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#103]
It's very easy to add support for forcefield-defined bond charge corrections, so I'm going to do that now, since it will enable dielectric corrections (timely with @cfennell's visit).
### API Proposal

I propose to extend the API of `ForceField.createSystem()` to add a `chargeMethod` argument, which can take one of the following values:
- `'BCC'` will apply bond charge corrections if the `ffxml` file had a `<BondChargeCorrections>` block. This first applies a semiempirical method (specified in the `method` attribute of the `<BondChargeCorrections>` XML block) and then applies bond charge corrections. If no `<BondChargeCorrections>` section is specified, the charges specified in the `OEMol` `molecules` are used.  **(default)**
- Any of the charge methods in `openeye.oequacpac` can be specified as a string (e.g. `'OECharges_AM1BCCSym'`), and this charge model will be used.
- `None` forces the charges from the provided `OEMol` `molecules` argument to be used. (useful for testing)
### XML specification

Rules:
- Later definitions that match the _same bond_ override earlier definitions. This is needed to ensure the definitions scheme is hierarchical, like other parts of SMARTY.
- Multiple definitions can be sequentially applied to the _same atom_.

``` XML
<BondChargeCorrections method="AM1" increment_unit="elementary_charge">
  <BondChargeCorrection smirks="[#6X4:1]-[#6X3a:2]" increment="+0.0073"/> <!-- tetrahedral carbon bonded to aromatic carbon correction -->
  <BondChargeCorrection smirks="[#6X4:1]-[#6X3a:2]-[#7]" increment="-0.0943"/> <!-- tetrahedral carbon bonded to aromatic carbon (bonded to a nitrogen) -->
</BondChargeCorrections>
```

where the `"AM1"` in `method` would be expanded to `OECharges_AM1` for `oechem.oequacpac` in our initial implementation.
### Example usage

Current scheme remains default: Take charges from `molecules`:

``` python
system = forcefield.createSystem(topology, molecules)
```

Use `ffxml`-defined bond charge corrections:

``` python
system = forcefield.createSystem(topology, molecules, chargeMethod='BCC')
```

Use recommended AM1-BCC from `oequacpac`:

``` python
system = forcefield.createSystem(topology, molecules, chargeMethod='OECharges_AM1BCCSym')
```

**Update:** Proposal tweaked so that any bond charge corrections in the file are automatically applied.

**Comment by jchodera** [comment]
Proposal above has been updated to reflect a change in default behavior.

**Comment by davidlmobley** [comment]
This looks viable to me, though we'll need @cbayly13 's eyes on it.

**Comment by jchodera** [comment]
Also, what best practices should we be following in assigning charges for different `chargeMethod` choices?

For `OECharges_AM1BCCSym`, is there a recommended conformational expansion that proceeds it? What about for other schemes, such as just applying `AM1` charges prior to assigning bond charge corrections?

**Comment by davidlmobley** [comment]
I'll go over what I think we need to do with @cbayly13 early in the week to confirm and then let you know (or submit a PR to implement). For now I suggest you just conformationally expand using omega with default parameters and plunge ahead

**Comment by davidlmobley** [comment]
@jchodera - I showed this to @cbayly13 ; he seems to think it is good. Not sure if he'll have any more detailed feedback but so far so good. 

He's looking at the charge/conformational expansion issue shortly.

**Comment by cbayly13** [comment]
I think the API proposal looks. I note that the application of the increment ( ie +increment to the first atom and -increment to the second) puts an order-dependence on the SMIRKS specification, but I think that is OK because atom:1 is specified and its label can't change. We should watch that.

**Comment by davidlmobley** [comment]
@jchodera : Regarding conformational expansion, YES, we need to add a conformational expansion:

> For OECharges_AM1BCCSym, is there a recommended conformational expansion that proceeds it? 

Yes! This only charges the provided conformer if it's given a single-conformer molecule; if it's given a multi-conformer molecule it does ELF1, per Christopher, which is currently the best available. So, we need to pass it a multi-conformer molecule, and the conformer generation should be done exactly as following this recipe: http://docs.eyesopen.com/toolkits/cookbook/python/modeling/am1-bcc.html

A side note is that ELF10 is better for large, flexible molecules with substantial conformational dependence in their charges, but this will not be available until the February toolkit release. At that time, there will also be a major change to the charging functionality where it will switch from being OEAssignPartialCharges to OEAssignCharges or something along those lines. So we'll know when it becomes available because our code will break with the latest toolkits.

**Comment by davidlmobley** [comment]
Did you want me to implement this, @jchodera ?

**Comment by jchodera** [comment]
Please do! 

I think we want to encapsulate this in the [`_assignPartialCharges()`](https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L515-L529) method which was intended to encapsulate whatever best practices go into charge assignment given the `oechargemethod` provided.

Thanks!

**Comment by davidlmobley** [comment]
This was all implemented; closing.
