### ISSUE TITLE
Only python 2.7 is being tested by travis

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#107]
I ran into a few surprising python 3.x incompatibilities when trying to use `smarty` in https://github.com/open-forcefield-group/open-forcefield-tools.

It looks like only `python 2.7` is actually being tested in the travis branches for other python versions. I'll fix this in my PR #104.

**Comment by bannanc** [comment]
I think this was fixed in #104 correct?

**Comment by jchodera** [comment]
Yes!

**Comment by bannanc** [comment]
So it's ok to close it right?
