### ISSUE TITLE
Reminder: Please try to write python 3.x compliant code

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#108]
I just noticed the travis tests weren't actually testing against python 3.x (#107)

This has been fixed in #104, so tests should fail if we break python 3.x compatibility in the future.

**Comment by davidlmobley** [comment]
I still mostly use python2.7 locally, so there are some python3.x compliance issues I overlook. I've mostly adjusted to print functions, but it looks like there were some dictionary key issues I wasn't aware of. 

Glad to hear Travis is now testing against 3.x, as I've been relying on that to teach me. :)

**Comment by jchodera** [comment]
None of the new IPython notebook versions will have python 2.x releases, so you'll be stuck with 5.x in perpetuity:

https://python3statement.github.io/

We should get things in order sooner rather than later!
