### ISSUE TITLE
Implement set of proposals not to try again / short term application: avoid retrying unused base cases

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#11]
We should implement tracking of patterns not to try again (I may have seen this listed as a `to do` somewhere in the existing code as well). The most immediate use for it is to track base types not to try again - i.e. if there are no chlorines in our set (AlkEthOH for example) there will never be, so there is no need to keep attempting them. Presumably we will use this for other things in the future as well.

**Comment by jchodera** [comment]
I believe I implemented this exact feature a little while ago:
https://github.com/open-forcefield-group/smarty/blob/master/smarty/sampler.py#L139-L141

**Comment by davidlmobley** [comment]
This does seem to be implemented at present; I have verified that atom types which are destroyed are not created again (i.e. bromine in AlkEthOH).
