### ISSUE TITLE
Reprocessing full trajectory to reflect changes in forcefield parameters

### ISSUE THREAD

**Issue by bmanubay** [open-forcefield-group/smarty#111]
Hey @jchodera,

If I had some stored trajectory output from an OpenMM simulation using SMIRFF and wanted to reprocess the energies to reflect parameter changes that I had made to SMIRFF (like I'm doing now as I evaluate changes in the uncertainty of energy across parameter space). Is there a way to do that without running a new simulation? Maybe by manipulating the simulation context? Thanks!

**Comment by davidlmobley** [comment]
Note that this is a general OpenMM question, and independent of SMIRFF. It's just a "how do I reprocess" question. (But I don't know the answer, having not done this yet.)

**Comment by jchodera** [comment]
Yes, it's incredibly easy. I'm not sure how you stored your trajectory data, but you just need an idiom like

``` python
import np
from simtk import openmm, unit
import smarty
# Create your new System object with updated parameters
forcefield = smarty.ForceField(ffxml) # load your new forcefield file with modified parameters, if needed
system = smarty.ForceField(topology, molecules) # you have to have the Topology and OEMols available
# Create an OpenMM
integrator = openmm.Integrator(1.0 * unit.femtoseconds) # any integrator will do since we're not doing dynamics
context = openmm.Context(system, integrator)
reduced_potentials = np.zeros([nsnapshots], np.float64) # store reduced potentials
for index in range(nsnapshots):
    # set the positions
    context.setPositions(snapshot[index])
    # get the energy
    potential_energy = context.getState(getEnergy=True).getPotentialEnergy() # has units
    # store reduced potential
    reduced_potentials[index] = potential_energy / kT
```

That's it!

**Comment by bmanubay** [comment]
Thanks @jchodera! @davidlmobley pointed out that that should be how it works. Examples are always welcome though!
