### ISSUE TITLE
Potential issue with impropers in ForceField

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#122]
Quite by accident, I discovered that if I have an FFXML file which contains a generic improper such as
`<Improper smirks="[*:1]~[*:2]~[*:3]~[*:4]" id="i0" k1="1000" periodicity1="2" phase1="180."/>`

then no proper torsions get assigned to my molecules, only the above improper.

This may not be a major issue since most "realistic" impropers wouldn't actually match patterns that torsions would match, I think. BUT, it probably also means there is a bug in handling of torsions/impropers in `ForceField`.

**Comment by davidlmobley** [comment]
OK, on further investigating/thinking about it, I don't think this is actually a bug, but really a "user error". Specifically, my SMIRKS pattern is incorrect for an improper. Our convention in SMIRFF is that the central atom is the second atom, so an improper would be formed as `[*:1]~[*:2](~[*:3])~[*:4]`, NOT `[*:1]~[*:2]~[*:3]~[*:4]`, as the latter matches torsions. If it occurs in a SMIRFF file following the propers, all propers will be overwritten by the generic. 

So, probably I need to implement "improper checking" in SMIRFF to ensure that all impropers are properly formed with the second atom as the central atom. I'll have to bug @bannanc to see if she knows the easiest way to do this.

**Comment by davidlmobley** [comment]
Somewhat relatedly, there is a note in the code asking whether we need to handle propers and impropers differently. I think the answer is "no" except that impropers need to be checked to see if they are well formed, to avoid gobbling up propers. https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L1392

**Comment by davidlmobley** [comment]
I think the fix (for safety) to the issue here is to have `periodicTorsionGenerator.createForce` do a separate check for impropers to ensure they are correctly formed (the second atom is central). Otherwise, sooner or later, someone is likely to accidentally omit a branch in an improper and have it gobble up a bunch of their torsions.

**Comment by bannanc** [comment]
I have a built in check with environment objects that if you initiate them with a SMIRKS string the type should match the object you initiated. So if you create a `ImproperChemicalEnvironment` with a SMIRKS that's not for an improper it should raise a SMIRKSMisMatchError, example below:

```
import smarty.environment as env
smirks = "[*:1]~[*:2]~[*:3]~[*:4]" 
improper = env.ImproperChemicalEnvironment(smirks)

SMIRKSMismatchError: (SMIRKSMismatchError(...), 'The SMIRKS ([*:1]~[*:2]~[*:3]~[*:4]) was assigned the type Torsion when Improper was expected')
```

Alternatively if you don't want to check for the error, you can use the base chemical environment and then check the type, something like:

```
import smarty.environment as env
smirks = "[*:1]~[*:2]~[*:3]~[*:4]" 
improper = env.ChemicalEnvironment(smirks)
type = improper.getType( )
if type != "Improper":
    # However you want to handle the case
```

**Comment by davidlmobley** [comment]
Thanks, @bannanc !

**Comment by davidlmobley** [comment]
Thanks, @bannanc . I just used this to check that torsions are of the correct type in #143 -- i.e. no propers labeled as impropers or vise versa.
