### ISSUE TITLE
Pull basic boron parameters

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#139]
In the interests of ensuring coverage, @bannanc , we should probably get basic boron parameters into the smirff99Frosst parameter set. We can probably just pull what GAFF uses and adopt. (Or do you already have something?)

Thanks.

**Comment by bannanc** [comment]
I was not aware that parm@Frosst didn't cover boron, I'm not seeing it in the smirff99Frosst.ffxml file. I will look up the GAFF parameters for boron.

**Comment by davidlmobley** [comment]
Thanks, @bannanc . Christopher had said he'd felt he should have put boron parameters into parm@frosst but he never got around to it.

**Comment by bannanc** [comment]
@davidlmobley 
I never did this, did you?
Shouldn't this issue be in the SMIRNOFF directory?

**Comment by davidlmobley** [comment]
This wasn't done yet, @bannanc . I think it has to be dealt with here because the materials to create/update smirff99Frosst and derivatives (from `frcmod`/`parm`-like files in the AMBER style are in this repo.  We still don't want to be editing the ffxml directly as we expect more updates coming in from AMBER-like formats.

Alternatively, you can just grab the parameters, stick here, and I can probably take care of it. :)

**Comment by davidlmobley** [comment]
Oops, I see you assigned me. That's fine, I can do it, @bannanc .

**Comment by bannanc** [comment]
@davidlmobley I assigned us both, I was going to see if you had time to do it, if you don't I'll add it to my list. 

I hadn't thought much about the force field until Nam started using it on the OFF-compare project, it looks like there are some weird conformations happening with sulfur.

**Comment by bannanc** [comment]
@davidlmobley 
I sort of feel like I'm missing something, but I've looked at the gaff.dat and gaff2.dat files and I don't see anything for boron... 

Are we sure gaff covers boron?

**Comment by davidlmobley** [comment]
No. Oddly, I assumed it did, but it seems not to!

Can you pull some boron-containing compounds and send them Vickie's way? We can have her run some reference QM calculations and just pull bond lengths/angles directly from the QM in a coarse way, and make up some force constants that are consistent with similar bonds. Then we'll at least have basic parameters. (We can make do with fairly generic torsions as a starting point.) This will do as a starting point for fitting.

**Comment by bannanc** [comment]
@davidlmobley I mentioned this to Christopher today, he says that AM1BCC also doesn't charge molecules with Boron. The goal with smirnoff99Frosst is to cover the chemical space in existing force fields. Should we be spending time calculating parameters that don't exist in the current FFs?

**Comment by davidlmobley** [comment]
I also talked to Christopher about that, @bannanc , and there is a fallback option in the AM1-BCC calculation which can allow you to just get AM1 charges. I'd actually like to get boron in here for "current science" reasons -- Brian Shoichet is doing measurements of binding affinities of boron-based compounds in the lysozyme binding sites (rings containing the occasional boron rather than just phenyl rings); basically they "behave" very similar to compounds with only carbon except they have a bit more solubility so he can cover some R groups we had wanted to look at but which weren't soluble enough.

**Comment by bannanc** [comment]
Ok, when we're back I'll give some boron compounds to Vickie.  And get at least rough estimates available.

**Comment by davidlmobley** [comment]
Thanks! And we should ask Chris for the invocation to get AM1 charges from the AM1BCC calculation...

**Comment by jchodera** [comment]
I believe retrieving AM1 charges is already supported. See the [help here](https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L861-L899). If you specify one of the OpenEye charge methods for `chargeMethod` (e.g. `OECharges_AM1`) you will get just AM1 charges. If you specify `chargeMethod=BCC`, you'll get OpenEye-assigned AM1 and any listed `<BondChargeCorrection>` terms will be applied, which should handle your boron case.

**Comment by davidlmobley** [comment]
@jchodera - that's correct, but Chris said that there is a way to ask for AM1-BCC so that it will automatically fall back to AM1 charges for any atoms for which BCC parameters are not available. (By default, if you ask for AM1-BCC and BCC parameters are not available for some atom, it will just raise an exception, but it is possible to alter this behavior with the appropriate invocation apparently.)

**Comment by jchodera** [comment]
If you let `smarty.forcefield.ForceField` assign the BCC charges for you by setting `chargeMethod='BCC'` and specifying `<BondChargeCorrection>` parameters in the SMIRNOFF forcefield, it will do this for you automatically.

I guess you're looking for an `OECharges_` option that will let you pre-assign charges outside of SMIRNOFF with OpenEye tools instead?

**Comment by davidlmobley** [comment]
> If you let smarty.forcefield.ForceField assign the BCC charges for you by setting chargeMethod='BCC' and specifying <BondChargeCorrection> parameters in the SMIRNOFF forcefield, it will do this for you automatically.

Right, but then we'd have to dig up and specify all the BCC parameters, right? Though maybe that would not be hard -- have to see whether these are easily accessible in the original paper.

> I guess you're looking for an OECharges_ option that will let you pre-assign charges outside of SMIRNOFF with OpenEye tools instead?

That was the thought, yes.

**Comment by jchodera** [comment]
BCC atom types are [defined here](https://github.com/choderalab/ambermini/blob/master/share/amber/dat/antechamber/ATOMTYPE_BCC.DEF), and BCCs are [defined here](https://github.com/choderalab/ambermini/blob/master/share/amber/dat/antechamber/BCCPARM.DAT). I guess there are 405 BCCs defined (some of which are zero) and ~60 atom types.

**Comment by bannanc** [comment]
I have Boron included in issues on smirnoff99Frosst I don't think it should be covered in smarty anymore.
