### ISSUE TITLE
Plan infrastructure for parameter ID test

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#14]
Ultimately, we would like to move away from the "atom type" (or "vdw type") focus of the initial test and do a slightly more general test before moving to "real" chemistry -- particularly, we'd like to look at whether we can reproduce the **parameter types** from the parm@frosst set for AlkEthOH. This would require us to discover patterns which would reproduce vdW types as in the current `smarty`, but also reproduce bond types, angle types, and torsion types. This would test that our decoration machinery is able to handle the additional complexity that comes with that.

We'll need to think through how we would re-work/re-configure things ultimately to allow that -- probably this would basically be a step towards generating the machinery we would need for parameterizing to actual data. In this test, the existing `smarty` would be the answer to just one part of the test.

**Comment by davidlmobley** [comment]
This also means we should try as much as possible to avoid the idea of "atom types" except when **scoring** the results of smarty, both because it will make this test easier and because it will make it easier for us ultimately to abandon atom types completely. (Maybe this should be a separate issue?)

**Comment by davidlmobley** [comment]
This also relates to something which came up in the overly-broad issue #3 :

> > We're slowly trying to move away from smarty being just atomtypes, as the chemical perception will eventually need to handle atoms, bonds, angles, and torsions. That means reference type will be a list of atom types and atoms should be general matches. For now the scoring will likely be the fraction of reference types matches since we're still comparing to current atom types.
> > I had originally intended to write a completely different piece of code to do that, since this code has no facility for sampling over parameters, and building this in would be difficult since this capability is not modular with the current design.

I think we ought to be separating the issue of "sampling over parameters" from "handling chemical perception generally", as we ought to be able to do more than just "atom types" with smarty.

**Comment by jchodera** [comment]
Do you mean that you want to try to recover bond types in parm@frosst (e.g. `HS-SH`), or the bond energetics classes?

The recovery of bond, angle, and torsion types may not be meaningful because they are all based on atom types. We're trying to get _away_ from atom types and instead discover different classes of bonds that may be divorced from atom types.

If we want to get away from atom types in a SMIRKS-based bond match, how do we test this on something that is not fundamentally atomtype based if we don't use the energetics to score?

**Comment by davidlmobley** [comment]
> Do you mean that you want to try to recover bond types in parm@frosst (e.g. HS-SH), or the bond energetics classes?

Well, you COULD call it bond, angle, and torsional types, but really we were talking about seeing whether we could reproduce his hand-, expert-generated parameter types from parm@frosst on AlkEthOH. Specifically, from https://github.com/open-forcefield-group/open-forcefield-data/blob/master/Model-Systems/SMIRFF_prototype/smarff_mockup1.Frosst_AlkEthOH we'd look at this type of thing:

```
[#6X4]-[#6X4]    parBond  (1.526, 310.0) parNum b001 {CT-CT from frcmod.Frosst_AlkEthOH}
[#6X4]-[#1]      parBond  (1.090, 340.0) parNum b002 {CT-H_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H1] parBond  (1.410, 320.0) parNum b003 {CT-OH from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H0] parBond  (1.370, 320.0) parNum b004 {CT-OS from frcmod.Frosst_AlkEthOH}
[#8X2]-[#1]      parBond  (0.960, 553.0) parNum b005 {OH-HO from frcmod.Frosst_AlkEthOH}

# angles
[a,A]-[#6X4]-[a,A]   parAng (109.50, 50.0) parNum a001 {consensus matches all X-Csp3-X}
[#1]-[#6X4]-[#1]     parAng (109.50, 35.0) parNum a002 {H1-CT-H1 from frcmod.Frosst_AlkEthOH}
[#6X4]-[#6X4]-[#6X4] parAng (109.50, 40.0) parNum a003 {CT-CT-CT from frcmod.Frosst_AlkEthOH}
[#8X2]-[#6X4]-[#8X2] parAng (109.50, 70.0) parNum a004 {O_-CT-O_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#1]   parAng (108.50, 55.0) parNum a005 {CT-OH-HO from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#6X4] parAng (109.50, 60.0) parNum a006 {CT-OS-CT from frcmod.Frosst_AlkEthOH}

# torsions
[a,A]-[#6X4]-[#6X4]-[a,A]   parTor ( (9, 1.40, 0.0, 3) ) parNum t0001 {X -CT-CT-X from frcmod.Frosst_AlkEthOH}
...
```

etc.

The test would be, can we generate SMARTS (SMIRKS) patterns that will color the same parameter numbers, i.e. `a001`, `t001`, etc. These wouldn't need to match the same patterns he hand generated, but would they recognize the same bonds, angles, torsions, etc.? 

Basically, it's the same test as we're doing in Smarty, but (a) NOT using atom types, and (b) extended to handle bond, angle, and torsional types

> The recovery of bond, angle, and torsion types may not be meaningful because they are all based on atom types. We're trying to get away from atom types and instead discover different classes of bonds that may be divorced from atom types.

Ahh, but that's actually one of the great things about this SPECIFIC test - he's already gone through by hand (on AlkEthOH) and divorced the parameters from the normal notion of atom types, i.e. there are fewer torsions in his mockup than there would be if we used normal atom types, etc.

> If we want to get away from atom types in a SMIRKS-based bond match, how do we test this on something that is not fundamentally atomtype based if we don't use the energetics to score?

Hopefully the above clarifies.

**Comment by jchodera** [comment]
OK. I was suspecting this was what you meant, but wanted to be sure. It's fundamentally still atomtype-based (since it is just a direct translation of atom types into SMIRKS), but your goal is to just see how easy these hand-coded SMIRKS strings can be recovered with a Monte Carlo scheme.

Any thoughts on how the Monte Carlo sampling should work? I haven't thought through this deeply for the bond, angle, and torsion types.

**Comment by davidlmobley** [comment]
I think Chris has a pretty good idea how to do it, so I can pick his brain
more tomorrow. Is there anything specific you'd want to know?

Obviously being able to MC sample things more complicated than just vdW
types is going to be key when it comes to parameterizing to experimental
data, so we thought this would be a good thing to make sure we can do as
well.

On Mon, Jun 20, 2016 at 9:07 PM, John Chodera notifications@github.com
wrote:

> OK. I was suspecting this was what you meant, but wanted to be sure. It's
> fundamentally still atomtype-based (since it is just a direct translation
> of atom types into SMIRKS), but your goal is to just see how easy these
> hand-coded SMIRKS strings can be recovered with a Monte Carlo scheme.
> 
> Any thoughts on how the Monte Carlo sampling should work? I haven't
> thought through this deeply for the bond, angle, and torsion types.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/smarty/issues/14#issuecomment-227335564,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYR7u0XfriZAKsTJfpSKPQfjT-3g-ks5qN2NkgaJpZM4I6QSA
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
We specifically need a move set for constructing child proposals for bonds, angles, and torsions.
