### ISSUE TITLE
Consider creating the plots from smarty in smirky

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#141]
@camizanette has added a number of plots as output for smarty. Is there a version of this we would like to use in smirky as well? 

I think it makes more sense for them to be created out side the run function if we decide to incorporate them.

**Comment by davidlmobley** [comment]
I might have been the one who added the plots (I added some plots of score vs time). 

Yes, probably we will ultimately want that ability for smirky as well, though there's no rush.

**Comment by bannanc** [comment]
sorry, yes the plots you made are the ones I'm referring to. 

In smarty they are created inside the run function. I think they belong in their own function and possibly outside the sampler all together since they use the "trajectory" file as input it could just be added on to the end of the cli file

**Comment by davidlmobley** [comment]
Yes, I agree it doesn't make sense to have them in run. It was a hack. :(

**Comment by bannanc** [comment]
ok, at some point, in the hopefully not too distant future I'll look into adding them to cli_smirky

**Comment by bannanc** [comment]
see pull request #151

**Comment by bannanc** [comment]
in master with pull request #151
