### ISSUE TITLE
Functional forms for bonded interactions in the ffxml files

### ISSUE THREAD

**Issue by bmanubay** [open-forcefield-group/smarty#145]
Hey guys,

Is there anyway that the functional forms of the bonded interactions could be included with the forcefield data? I'm not sure if this would be best put directly into the ffxml or maybe in the README, but it would be nice to have them just for reference :)

Thanks!

**Comment by davidlmobley** [comment]
@bmanubay - this has overlap with #133 . I desperately need to create a page documenting the details of the FFXML format, what's implemented and how, etc. Additionally, this page should presumably either give the functional forms directly or link out to where this info is provided (most likely the latter). And a link to this documentation should be included in the FFXML files.

But, I won't get to writing this documentation until after Oct. 5, I expect. So in the meantime -- you should be able to consult the OpenMM documentation, as we're just implementing normal harmonic bonds and angles and periodic torsions as implemented in OpenMM. i.e., see section 19 here: http://docs.openmm.org/6.3.0/userguide/theory.html

**Comment by davidlmobley** [comment]
(How we specify the parameters is a little bit different, but they end up getting implemented in the same way. So if you have questions relating to how the parameters get specified, please follow up here.)

**Comment by bmanubay** [comment]
Got it! Thanks David!

**Comment by davidlmobley** [comment]
@bmanubay , I've written a draft of documentation on the FFXML format. Please see there and let me know if you have changes, or propose edits there: https://github.com/open-forcefield-group/smarty/wiki/The-SMIRFF-force-field-format

**Comment by jchodera** [comment]
This is great!

I don't believe the wiki is version-controlled. Can we move this into a markdown file in the actual repo and make PRs against it to refine it?

**Comment by davidlmobley** [comment]
That could work. One issue -- the reason I went with a wiki -- is that this doesn't have an obvious _place_ it should go in the repo. If you can tell me where that README.md should go I'm happy to migrate there, @jchodera .

**Comment by davidlmobley** [comment]
(Once that's sorted out it should be just a copy and paste to a README.md).

**Comment by jchodera** [comment]
> That could work. One issue -- the reason I went with a wiki -- is that this doesn't have an obvious place it should go in the repo. If you can tell me where that README.md should go I'm happy to migrate there, @jchodera .

I'd just create a top-level file called `The-SMIRFF-force-field-format.md` and link to it in the `README.md`. When someone clicks the link in the `README.md` or clicks on the `The-SMIRFF-force-field-format.md` file itself, it will render as a nice markdown file (but will be version-controlled).

**Comment by davidlmobley** [comment]
Ah, excellent, that's a much better idea. Didn't realize that github handled an "anything.md" file this way -- thought it was only README.md. That's awesome.

**Comment by davidlmobley** [comment]
(in hindsight that should have been obvious).

I'll move it over later today. Meeting now.

**Comment by jchodera** [comment]
Done in #160. Review and merge, then I'll take a pass through it in a separate PR.

**Comment by jchodera** [comment]
@bmanubay : Has the [SMIRNOFF spec](https://github.com/open-forcefield-group/openforcefield/blob/master/The-SMIRNOFF-force-field-format.md) covered your request, or did you want something else, like the ability to select different functional forms in the XML tags?

**Comment by bmanubay** [comment]
@jchodera : This is great for now; thanks John! Functional form selection is beyond the scope of what I'm working on currently. Might just be better to cross that bridge when we come to it farther down the line. :)
