### ISSUE TITLE
README in the molecules directory 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#156]
As we get more molecule test sets, I think it will be important to have better documentation of what each molecule file contains. Especially since names like test_filt1_tripos.mol2 isn't particularly informative. Not a high priority, but I think we should do this before any of the papers related to this repository are getting submitted.

**Comment by davidlmobley** [comment]
Agreed, yes. (If you still have spare time, feel free...)

**Comment by bannanc** [comment]
spare time isn't something I have a lot of write now, but if I get a chance I'll start one before my next pull request.

**Comment by bannanc** [comment]
I added in pull request #198
