### ISSUE TITLE
Add support for additional functional forms for vdW interactions

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#161]
We currently only support Lennard-Jones interactions, but it would be easy to generalize `NonbondedForce` beyond this to support Morse, Buckingham exp-6, Halgren buffered 14-7, and other functional forms.

**Comment by jchodera** [comment]
@ramess101 suggests in https://github.com/open-forcefield-group/smarty/issues/221
* the [generalized Lennard-Jones (m-n) potential](http://dx.doi.org/10.1023/A:1024798909685)
* the [Buckingham exp-6 potential](https://en.wikipedia.org/wiki/Buckingham_potential)

**Comment by bannanc** [comment]
Moved to openforcefield
