### ISSUE TITLE
Store additional by-iteration information for reuse in plots and subsequent analysis

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#17]
@cbayly13 has been monitoring a variety of information and is thinking about plotting this type of info in various ways. He would at least like to have access to, at each iteration:
- number of parameters (patterns) 
- score

He wants to end up with these in a `pandas` data frame to be able to do things like plot the number of patterns versus score, number of patterns versus iteration, score versus iteration, and so on. This has some overlap with issues raised in #3 and would implement one of the ideas in #15 .

The end goal is for him to end up with this in a `pandas` data frame, but I'm ambivalent at this point as to what the intermediate format would be. Currently he's running `awk` on log files (as output to the screen) which doesn't seem like the best longer-term solution.

**Comment by bannanc** [comment]
@davidlmobley 
I think this has been sufficiently addressed with store typenames and parents in the trajectory files so we could use them to rebuild scores for individual types, the total score, parent trees, etc. 
I'm closing for now.
