### ISSUE TITLE
Fix checks for missing parameters

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#170]
@jchodera - I was under the impression from what you wrote describing your initial code that an exception would be raised if parameters were missing for any of the major required force types in a molecule (i.e. bonds, angles, torsions, LJ), but this seems not to be the case in general. I see this being done for bonds (https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L1234) but for none of the other force terms.

I happened across this because I was starting with a specific SMIRFF and trying to make it more general, and I found that I had certain angle terms which simply HAD no angle parameters.

We'll either need to (ASAP) implement this checking, or make our basic SMIRFFs assign generic dummy parameters to all force terms and then check that these get overridden.

**Comment by jchodera** [comment]
Not a problem---I can add this right now.

I think I was hoping to get topological angle and torsion enumeration into `simtk.openmm.app.Topology` first, but then that dropped by the wayside. I'll add that to our `_Topology` class for now, and we can migrate those routines to OpenMM later.

**Important question:** What (if anything) do you want to do about checking for impropers?

**Comment by davidlmobley** [comment]
@jchodera - don't check impropers. I don't think we have any way at this point to tell when they should/shouldn't be applied. That will have to be revisited in a separate issue which will involve a lot more chemistry.

**Comment by jchodera** [comment]
OK, nearly done.

**Comment by jchodera** [comment]
Any suggestions for tests? Did you say you have an example of a deficient forcefield file that is missing some terms?

**Comment by davidlmobley** [comment]
Tests -- easiest would be to just take one of the existing sample forcefields under tests and remove some of the most generic parameters. Give me a moment and I'll give you something concrete.

**Comment by davidlmobley** [comment]
So, I'd propose you add a really simple test where you attempt to create a molecule from SMILES (say, `CCCC` or something similar) and make a dummy forcefield (like those in the top of `test_forcefield.py`) which is missing required parameters -- so, for example, use the initial "ffxml_contents" there but remove the first two angle parameters (a0001 and a0002), the generic torsion t0001, the torsions t0004 and t0005, and the nonbonded term for 6X4, n0008. Then check that the right exceptions get raised. Those removals should break angles, proper torsions, and nonbonded.

**Comment by jchodera** [comment]
This seems more complex than the original code changes. Do you mind if I open a PR and have you implement the tests? Happy to fix if tests fail, but it sounds like it would be more efficient for you to put in the tests.

**Comment by davidlmobley** [comment]
I could do that. It's not complicated at all though -- just pick some arbitrary simple molecule and delete some of the parameters it uses.

**Comment by jchodera** [comment]
Another question: What about `i-j-k-i` torsions for three-membered rings? Those should be excluded from torsions, right?

**Comment by davidlmobley** [comment]
Sorry, @jchodera - what do you mean by "excluded from torsions"? Do you mean that they don't count as a normal torsion? Or are you asking whether we should check whether they are assigned?

I believe they are valid torsions, but maybe I'm missing something.

**Comment by jchodera** [comment]
> I believe they are valid torsions, but maybe I'm missing something.

I don't think they can be---they can't ever be anything but 0 degrees.

**Comment by davidlmobley** [comment]
I agree they are not useful. But they are assigned by existing AMBER-style force fields, I believe.

(Specifically, if we apply the AlkEthOH ffxml to three-membered rings, we get exactly the same force terms as parm@frosst, right now, so unless we're NOT currently assigning these, it means that AMBER-style force fields ARE.)

**Comment by jchodera** [comment]
> I agree they are not useful. But they are assigned by existing AMBER-style force fields, I believe.

![alt text](https://otterlover58.files.wordpress.com/2015/04/calvin_headexplode.jpg)

**Comment by davidlmobley** [comment]
Haha. I have to run off in a minute but I can make a note to check tomorrow -- I'd just have to use the labeler on a sample molecule to see if we're assigning a torsion to those in AlkEthOH. Whatever we're doing exactly matches what AMBER is doing, so it's an easy check.

**Comment by davidlmobley** [comment]
If that makes your head explode, though, you should look at what happens to tetraphenylbenzene in GAFF and GAFF2 due to, er, human errors related to atom typing. Check out the pucker in the middle ring.

![macpymol](https://cloud.githubusercontent.com/assets/7132257/19709494/de5b0166-9adb-11e6-9b72-0f79177e3b25.jpg)

**Comment by davidlmobley** [comment]
> Another question: What about i-j-k-i torsions for three-membered rings? Those should be excluded from torsions, right?

OK, @jchodera - looks like my earlier comments were mistaken. For i-j-k-i torsions for three-membered rings, neither us nor AMBER are currently assigning these. So we'll need to NOT look for parameters being assigned for those.

**Comment by jchodera** [comment]
Got it. We now exclude checks for i-j-k-i torsions in the PR I created.
