### ISSUE TITLE
Fixing failing travis builds

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#174]
Just a heads-up that github nightly builds are about to start failing because the miniconda webpage has migrated from `http://` to `https://`.

If you need to patch things yourself, use this fix:
https://github.com/choderalab/alchemy/pull/53/files

I'll try to patch as many as I can over the next 24 hours.

**Comment by davidlmobley** [comment]
I fixed this and forgot to note it, IIRC.
