### ISSUE TITLE
Decouple smarty from ForceField/SMIRFF for versioning

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#175]
We'll need to move to get the Smirks force field format into a separate repo for versioning reasons -- specifically, we'll need to start versioning the specifications for the format, and having the parsing code check that the version of the XML being parsed is consistent with the version of the parser doing the parsing. But @jchodera points out that we don't want to have to cut a new version of the spec every time we change something in smarty or smirky, hence a need to separate the two now.

@jchodera says he will tackle this soon.

**Comment by davidlmobley** [comment]
@jchodera - now that #239 is merged you should be able to proceed with this.

**Comment by jchodera** [comment]
Unless there are objections, the new repository will be called https://github.com/open-forcefield-group/smirnoff

**Comment by davidlmobley** [comment]
Excellent, @jchodera !

I'm mostly offline today but will try and scroll through my mass of github notifications really quickly to see if there is anything urgent.

**Comment by jchodera** [comment]
I'm trying to see if there's a way to preserve commit history during the migration. Stay tuned!

**Comment by bannanc** [comment]
@jchodera @davidlmobley I think this can be closed since smarty/smirnoff99Frosst/openforcefield should all have their own versions now correct?

**Comment by davidlmobley** [comment]
Yes. Thanks.
