### ISSUE TITLE
Add a check that ensures that at least one torsional phase is applied

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#176]
I just ran into an issue where specifying `phase` rather than `phase1` for a torsion resulted in a silent error where no parameter was assigned for the torsion but all in-code checks passed -- the torsion is still listed as present (hence checking that the relevant valence terms are present passes), but the periodicity, phase, and k are not saved so it essentially it's an empty torsion which is never applied.

This should be fixed by requiring the length of the periodicity, phase, and k lists within a torsion to be nonzero, I think.  Or we could *always* process `phase1` and then process additional phases only if present. (Right now we process `phaseN` for any consecutive integer beginning with 1 upwards, as long as the phase is present, so if `phase` is not present, no phases are processed.)

**Comment by jchodera** [comment]
Good catch. 

We can add a check for the number of phases read [here](https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L1542-L1552).

Adding a sanity check that all `N` in the specified `phaseN` be consecutive is probably a useful idea.
