### ISSUE TITLE
Fix formatting in smarty/forcefield.py

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#177]
There are currently some departures from formatting conventions in [`smarty/forcefield.py`](https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py) (like [incorrect indenting in comments](https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L691-L700)) that should be cleaned up.

**Comment by bannanc** [comment]
Given how many changes have been made to forcefield.py since this was written, I'm going to close this here, we should make a new issue on [openforcefield](https://github.com/openforcefield/openforcefield) if necessary.
