### ISSUE TITLE
Fix naming (?) issue with OpenMM nonbonded force methods

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#185]
I'm getting an exception relating to a name change (?) of a `NonbondedForce` type on system creation, probably a change in the OpenMM API in version 7:

```
/Users/dmobley/anaconda/lib/python2.7/site-packages/smarty-0.1.4-py2.7.egg/smarty/forcefield.pyc in createForce(self, system, topology, nonbondedMethod, nonbondedCutoff, verbose, **args)
   1814                      PME:openmm.NonbondedForce.PME}
   1815         if nonbondedMethod not in methodMap:
-> 1816             raise ValueError('Illegal nonbonded method for NonbondedForce')
   1817         force = openmm.NonbondedForce()
   1818         force.setNonbondedMethod(methodMap[nonbondedMethod])

ValueError: Illegal nonbonded method for NonbondedForce
```

Investigating.

**Comment by davidlmobley** [comment]
Non-issue, I had bad arguments to a function call.

**Comment by jchodera** [comment]
> Non-issue, I had bad arguments to a function call.

I find these sorts of errors great opportunities to add some checking of the input arguments to return more helpful error messages for when I do it again next time. :)

**Comment by davidlmobley** [comment]
Already done in #187 , yes.
