### ISSUE TITLE
Trouble with smarty/smirky "trajectory" files

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#189]
I had a smirky run on our cluster time out and realized an improvement that should be made on the way the "trajectory" files are output on both smirky and smarty. 

Right now the data for "trajectory" files are saved as a list in the run function instead of just writing to the output file during each step. I don't think this ideal for memory. Also it means we have no trajectory file for simulations that run out of time, which is just wasting computer time. 

I'm working on fixing this on smirky right now. 

@camizanette I can fix this on smarty as well. However, I noticed some other issues with the smarty trajectory file that I thought we had fixed in both samplers, but maybe didn't get moved over to the element decomposition? 

1. In smirky, the trajectory file tracks the total score as well as the score by parameter type created, I thought we were going to add this to smarty as well. 

2. In the smarty trajectories, there are `0` for ParNum and ParentParNum. In smirky I am just using the parameter "typename" in both of these columns with quotes around the name. 

I'm happy to make the changes on the two smarty samplers as well. At the very least before we start any more simulations we should change the way the trajectory output is handled...

**Comment by davidlmobley** [comment]
This sounds good/important, @bannanc . Thanks for working on it.

**Comment by davidlmobley** [comment]
@bannanc - this was resolved by #190, yes?

**Comment by bannanc** [comment]
yes!
