### ISSUE TITLE
Rename SMIRFF stuff to SMIRNOFF

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#193]
@jchodera had strong objections to the Smirks Force Field (SMIRFF) name for the forcefield format, so after discussing with him and Christopher Bayly and others in person, we came up with an alternative acronym that he's happier with: SMIRNOFF, for Smirks Native Open Force Field. 

So, I need to update things here and on github.com/open-forcefield-group/smirff99frosst to reflect this. 

One key question -- when written out, should it be "Smirks-Native Open Force Field" or "Smirks Native Open Force Field"?

**Comment by bannanc** [comment]
I don't have a strong preference on the hyphen or no hyphen, but make sure SMIRKS is all caps.

**Comment by jchodera** [comment]
This has happened complete in the new repo: http://github.com/open-forcefield-group/smirnoff
