### ISSUE TITLE
Conda installing 0.1.4?

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#197]
@jchodera - via `conda`, we're still getting 0.1.2 from Omnia rather than 0.1.4. Is there something we have to do to get the build to update? @limn1 is having issues with this when attempting to get it going on Orion to use the SMIRNOFF forcefields.

**Comment by jchodera** [comment]
Fixed by updating the conda recipe: https://github.com/omnia-md/conda-recipes/pull/673

Note that you have to do this for each release you want to build.

**Comment by davidlmobley** [comment]
Yes, I'd forgotten that, but then figured it out again yesterday. Thanks.
