### ISSUE TITLE
Elemental Sampler scoring incorrectly

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#202]
I'm still investigating, because this doesn't seem to be happening consistently, but there appears to be some inconsistencies in how the SMARTY elemental sampler is scoring matches. 

I'm going to walk through a few things that I think are problematic about the way the elemental sampler is working. Some of this is scoring, the rest is just cleanliness and efficiency. These are mostly in the order they occur since I'm following the output. 

This example output comes from a simulation looking for hydrogen atomtypes in the CHO molecule set at temperature = 0. 

### Set up 
```
Atom type matches:
c_hydrogen                                                       matches       HC :    10054 atoms matched
c_carbon                                                         matches       CT :     7269 atoms matched
c_nitrogen                                                               no match
c_oxygen                                                         matches       OH :     1730 atoms matched
c_fluorine                                                               no match
```
...
```
19053 / 16917 total atoms match (112.626 %)
```
...
```
Storing base atom type `[#53]`, which is unused, so that it will not be proposed further.
Storing used atomtype `[#1]`, name `c_hydrogen` with count 16917...
Storing used atomtype `[#6]`, name `c_carbon` with count 12017...
Storing used atomtype `[#8]`, name `c_oxygen` with count 3458...
```

- Why are we bothering to check or store anything that isn't the element number being sampled?
- Another thing to note from this section is that there are **16917** hydrogen atoms **10054 HC atoms** I will use these for checking consistency later (assuming these counts are correct). 
- ~there is a statement about total atoms matched that compares the number of total atoms to the number of hydrogens which is what leads to that 112.626%...~
- nevermind there are 32392  total atoms, I don't know where the 19053 number came from

### Scoring initial types
```
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS REF TYPE        FRACTION OF REF TYPED MOLECULES MATCHED
    1 :      16917        780 |                                                       c_hydrogen                             [#1]       HC            10054 /            10054 (100.000%)
TOTAL :      16917        780 |                                                                                                       16917 /    16917 match (100.000 %)
```
Those lines are long to look at for github, but this is matching the generic/base hydrogen [#1] to HC, which makes sense. For individual atomtype we get what we expect that is *100% or 10054/10054* because [#1] matches all of the HC atoms. That part seems fine. For the total we would expect **10054/16917** since each current atomtype can only match one reference atomtype. However, the total recorded is given as **16917/16917** or 100% so something isn't tracking correctly. 

### Corresponding line in the Trajectory
```
Iteration,Index,Smarts,ParNum,ParentParNum,RefType,Matches,Molecules,FractionMatched,Denominator
0,1,'[#1]','c_hydrogen','None','HC',16917,780,10054,10054
0,-1,'total','all','None','all',16917,780,16917,32392
```
These were not written to be human readable so here is a translation:
- [#1] atomtype matches 16917 atoms in 780 molecules, but is scored based on the HC reference so it gets 10054/10054 
- the total/combined score there are 16917 atoms in 780 molecules, and the atomtypes listed above match 16917/32392 atoms

### What I know and don't know
- I know what is wrong with the denominator in the total line of the trajectory. The samplers have a variable called `self.total_atoms` since this is an elemental sampler, I assumed it only counted the atoms we cared about, this obviously isn't the case
- For both the commandline output and the trajectory file, my understanding was that the elemental sampler followed the same schematic as the original sampler, I haven't dug deeply into the code yet (that's next on my list). I don't think we ever ran into this issue with the original sampler. I will post more as I find where the bug is. 
- *there is still a typo where single bonds are referred to as "simply bonded" instead of "singly bonded"*

**Comment by bannanc** [comment]
Should we add a "it's not 100% test" or is this a temporary bug we don't think will be repeated.

**Comment by bannanc** [comment]
Looking further into this, in this log file, this is the first iteration where the score is reported correctly:

```
Iteration 9 / 1000
****** Got this element '1'.
Attempting to create new subtype: '[#1]' (c_hydrogen) + 'H0' (total-h-count-0) -> '[#1H0]' (c_hydrogen total-h-count-0)
Proposal is valid...
Creating graph matching current atom types with reference atom types...
Graph creation took 0.621 s
Computing maximum weight match...
Maximum weight match took 0.002 s
PROPOSED:
Atom type matches:
c_hydrogen                                                               no match
c_hydrogen total-h-count-0                                       matches       HC :    10054 atoms matched
10054 / 16917 total atoms match (59.431 %)
Proposal score: 16917 >> 10054 : log_P_accept = -6.86300e+03
Creating graph matching current atom types with reference atom types...
Graph creation took 0.573 s
Computing maximum weight match...
Maximum weight match took 0.001 s
PROPOSED:
Atom type matches:
c_hydrogen                                                       matches       HC :    10054 atoms matched
10054 / 16917 total atoms match (59.431 %)
Rejected.
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS REF TYPE        FRACTION OF REF TYPED MOLECULES MATCHED
    1 :      16917        780 |                                                       c_hydrogen                             [#1]       HC            10054 /            10054 (100.000%)
TOTAL :      16917        780 |                                                                                                       10054 /    16917 match (59.431 %)
```

This is also the first iteration to make it the "score comparing phase." That is to say the other iterations are rejected based on things like the new atomtype doesn't match any atoms or you can't destroy a basetype. This is leading toward a conclusion that there might be some kind of update that happens during scoring that wasn't done correctly in the initialization. It looks like this is rejected because of a decrease in score at 0 temperature when really the score is staying the same, but is now reported correctly. 

Here is the corresponding lines form the trajectory file:
```
Iteration,Index,Smarts,ParNum,ParentParNum,RefType,Matches,Molecules,FractionMatched,Denominator
9,1,'[#1]','c_hydrogen','None','HC',16917,780,10054,10054
9,-1,'total','all','None','all',16917,780,10054,32392
```
Note the total "FractionMatched" here is also correct, though the confusion with the denominator still exists.

**Comment by bannanc** [comment]
I ran a script that looked for files that had a 100% score on the first iteration, It looks like most of them that did not reached the "score comparing phase" in the first iteration.

**Comment by davidlmobley** [comment]
@bannanc - I'm reviewing your notes. A few responses:

> Why are we bothering to check or store anything that isn't the element number being sampled?

We shouldn't be, unless doing so simplifies the code so much that it isn't worth the investment of human time to bypass. 

I agree that after setup, in your example above, the total should be `10054/16917` and so much less than 100%. If the total is initially 100% then something is being scored incorrectly. 

> Should we add a "it's not 100% test" or is this a temporary bug we don't think will be repeated.

How would you test for this? Put in a case like this initial setup and ensure that the score is (a) correct, and (b) not 100%? It is probably good to put in a case where we know what the score ought to be and it is less than 100%, yes.

It sounds like something is initializing incorrectly, then getting corrected later. Do you need me to have a look at the code? I think I've read the `smarty` code somewhat more closely than you, @bannanc , so it's possible I might be able to spot something. Though it's been a long time.

**Comment by bannanc** [comment]
> How would you test for this? Put in a case like this initial setup and ensure that the score is (a) correct, and (b) not 100%? It is probably good to put in a case where we know what the score ought to be and it is less than 100%, yes.

That is approximately what I was thinking. When we get the tests with pandas working I can add a test that looks at the total score for the first iteration and checks that it is not 100%. 

> It sounds like something is initializing incorrectly, then getting corrected later. Do you need me to have a look at the code? I think I've read the smarty code somewhat more closely than you, @bannanc , so it's possible I might be able to spot something. Though it's been a long time.

I think we can clean up the code a bit so that it doesn't have to look at elements that are not the one being sampled, which will take a little work, but I think I know how to do it. I'm under the impression I was the last one to change anything in smarty since I fixed the trajectory output (albeit slightly incorrectly) in November.

**Comment by davidlmobley** [comment]
Yes, I don't believe there have been any changes in `smarty` since then.

I have the `pandas`/travis issue on my short list to look at so hopefully will get to it soon.

**Comment by bannanc** [comment]
I'm adding this for the record, there is a way to loop through only atoms of a certain element number using OpenEye:
```
atomicNum = 1
for atom in mol.GetAtoms(OEHasAtomicNum(atomicNum)):
    # do something in the loop
```

This means it should be easy to rework everything in the elemental sampler to only look at atoms of the given element number. That should clean up the code significantly as we will only be keeping track of atoms with the given elemental number.

**Comment by bannanc** [comment]
Significant changes as of #198
