### ISSUE TITLE
Ideal changes for smarty sampler

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#208]
I have a pull request open already, #198 that is addressing changes to the smarty original and elemental sampler.
In the process of investigating the best way to setup the elemental sampler, I've come across a few other minor issues that I will fix in this pull request, I wanted to have a list of them in an issue for prosperity sake. 

1. It seems that we were not consistent in creating atomtype lists. Some were created as list of tuples and others as list of lists. @davidlmobley is there a preferred form for this? They all have the same general format as a list containing pairs of SMARTS and labels for a created atomtype. 

2. When choosing a random atomtype, the index is chosen randomly, then the atomtype at that index is taken. 
If you use the random module from numpy, then the random choice option expects a list in 1 dimension and it won't choose a random choice for a list of lists or a list of tuples. 
In the smarty samplers though, we are using the stand alone random module, not the one that comes with numpy. When you use that random.choice with a list of lists it returns a sub list (or sub tuple if you use a list of tuples).

**Comment by bannanc** [comment]
@davidlmobley 
I'm also noticing there are some things being imported that don't seem to be used, maybe we need them somewhere I'm not familiar with, or maybe Camila or John used them while testing. Here are the modules, I'm not seeing being used:

sys
string
math

optparse is imported in the sampler.py, but is only used by cli_smarty.py does it need to be imported here too?

**Comment by bannanc** [comment]
There is some inconsistency with method doc strings I'm trying to repair as well

**Comment by davidlmobley** [comment]
Sorry for the delay, @bannanc . Responses:

> It seems that we were not consistent in creating atomtype lists. Some were created as list of tuples and others as list of lists. @davidlmobley is there a preferred form for this? They all have the same general format as a list containing pairs of SMARTS and labels for a created atomtype.

No, I don't think so. 

Regarding potentially unused modules `sys`, `string`, and `math`, I am not aware of using these. Simplest would probably be to `grep` the main code for their use, or just remove them and ensure things still work.

Regarding `optparse` - it should only be imported where it is needed, so if it's imported elsewhere that's unnecessary.

**Comment by bannanc** [comment]
I decided to use tuples, I think all atomlists are now lists of tuples.

I removed any of the imported modules not used in the smarty and smirky sampler. The tests seem to be passing so I assume they really were unnecessary.

I have also updated the doc strings (mostly in the smarty sampler).

**Comment by bannanc** [comment]
updated in pull request #198
