### ISSUE TITLE
Enhance efficiency of move proposals via adjacency improvements

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#21]
As in #11 , certain elements and/or SMARTS patterns simply won't occur in a given molecule set - i.e., there are no halogens in AlkEthOH. Currently we track which SMARTS patterns match no molecules, and we avoid re-trying them, so once bromine is destroyed in the AlkEthOH example, it never returns.

However, this tracking is not used for generation of NEW SMARTS strings - so, even though we know that bromine doesn't occur, we still check to see if carbon bromine-adjacent occurs:

```
Iteration 483 / 500
Attempting to create new subtype: '[#6]' (carbon) + '$(*~[#35])' (bromine-adjacent) -> '[#6&$(*~[#35])]' (carbon bromine-adjacent)
Atom type '[#6&$(*~[#35])]' (carbon bromine-adjacent) unused in dataset; rejecting.
```

Presumably once we have a SMARTS string which doesn't match anything (`[#35]` here), we also know that further decoration of that SMARTS will also not match anything, so we should not try "carbon bromine-adjacent" if we've already rejected "bromine".

**Comment by cbayly13** [comment]
Maybe this will go away all by itself once we use binary decorators for adjacency. Now "bound to a bromine" is the explicit decorator added in David's example. With binary decorators, we would get "bound to a..." and then or set of possible atoms won't include bromine because it is gone for both basetypes and the current list.

**Comment by davidlmobley** [comment]
@camizanette - see this and #13 .

**Comment by jchodera** [comment]
We could certainly eliminate decorators from consideration if we can perform a simple check that they never occur in the dataset. This could be done during initialization.
