### ISSUE TITLE
SMARTY and SMIRKY examples

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#210]
In all the other issues that came up during pull request #198 I realized I forgot to update the smarty example in examples. The current smarty example is very out data, it doesn't have a trajectory file or any reference to the elemental sampling options. 
The smirky one could also used some cleaning up too.

**Comment by davidlmobley** [comment]
Yes, would be good to have updated examples.

**Comment by bannanc** [comment]
Updated in pull request #212
