### ISSUE TITLE
Duplicate Typenames lead to scoring errors

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#211]
It took a while for me to find what was wrong (you can see the process of that below)

In summary if more than one atomtype has an identical typename it will be counted twice since the typename is what is used to assign the current types to an atom and then used to score. So if there are 2+ atomtypes with the same typename there are resulting score problems. 

I'm looking more closely at my tests with the updated smarty code. 
I'm getting scores that are > 100% on some elemental and all atom tests with PhEthOH. 
I didn't have any of these cases with AlkEthOH so I need to figure out what changed with this set of molecules. 

I'll post more details as I investigate further.

**Comment by bannanc** [comment]
fyi @davidlmobley

**Comment by bannanc** [comment]
Here is an example iteration with > 100% 

```
Iteration 1155 / 10000
Attempting to create new subtype: '[#6]' (c_carbon) + 'a' (aromatic) -> '[#6a]' (c_carbon aromatic)
Proposal is valid...
Creating graph matching current atom types with reference atom types...
Graph creation took 0.102 s
Computing maximum weight match...
Maximum weight match took 0.005 s
PROPOSED:
Atom type matches:
c_hydrogen                                                       matches       HC :     1565 atoms matched
c_carbon                                                         matches       CT :     1736 atoms matched
c_carbon aromatic                                                matches       CA :      708 atoms matched
c_oxygen                                                         matches       OH :      116 atoms matched
c_hydrogen singly c_carbon aromatic                              matches       HA :      532 atoms matched
c_hydrogen any c_carbon singly c_hydrogen (singly c_oxygen) (singly c_oxygen) matches       H2 :      250 atoms matched
c_hydrogen any c_carbon singly c_hydrogen (singly c_oxygen) (any c_carbon) matches       H1 :     1144 atoms matched
c_oxygen total-h-count-0                                         matches       OS :      613 atoms matched
c_carbon aromatic                                                matches       CA :      708 atoms matched
7372 / 7185 total atoms match (102.603 %)
Proposal score: 6664 >> 7372 : log_P_accept = 9.85386e+00
Accepted.
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS REF TYPE        FRACTION OF REF TYPED MOLECULES MATCHED
    1 :       2086        200 |                                                       c_hydrogen                             [#1]       HC             1565 /             1565 (100.000%)
    2 :       1736        200 |                                                         c_carbon                             [#6]       CT             1736 /             1736 (100.000%)
    3 :        708        108 |                                                c_carbon aromatic                           [#6&a]       CA              708 /              708 (100.000%)
    4 :        116        106 |                                                         c_oxygen                             [#8]       OH              116 /              116 (100.000%)
    5 :        532        108 |                             c_hydrogen singly c_carbon aromatic                   [#1$(*-[#6&a])]       HA              532 /              532 (100.000%)
    6 :        250        112 | c_hydrogen any c_carbon singly c_hydrogen (singly c_oxygen) (singly c_oxygen) [#1$(*~[#6](-[#8])(-[#8])-[#1])]       H2              250 /              274 ( 91.241%)
    7 :       1144        200 | c_hydrogen any c_carbon singly c_hydrogen (singly c_oxygen) (any c_carbon) [#1$(*~[#6](~[#6])(-[#8])-[#1])]       H1             1144 /             1525 ( 75.016%)
    8 :        613        200 |                                         c_oxygen total-h-count-0                           [#8H0]       OS              613 /              613 (100.000%)
    9 :        708        108 |                                                c_carbon aromatic                            [#6a]       CA              708 /              708 (100.000%)
TOTAL :       7893        200 |                                                                                                        7372 /     7185 match (102.603 %)
```

From what I can tell so far, the only issue is in how the "numerator" of the total is calculated. It should be the sum of the numerators above, but it isn't.
In this case the numerators add up to 6,664 which seems more accurate. 
I'm looking at the code now, this isn't a section I changed, but it must depend on something I did change.

**Comment by bannanc** [comment]
Ok, I missed it until I looked at the previous iteration where the the total score is what I expected in the example above. 

There are ***TWO CA*** atomtypes listed in the references above.

I am trying to figure out what I changed that allowed this to happen.
Note the "basetypes" used here ( found at smarty/data/atomtypes/basetype.smarts) has an aromatic carbon, I found it after I finished these tests. 
So the "basetype" aromatic carbon should have been emptied by this move and caused no change in score. 

It should be noted, that this is bigger than a summing error, something is going on in or around the best_match_reference_types method

I did change the requirements to not allow any empty atoms unless they were a base type, but we still shouldn't be allowed to keep an edge in the bi-partite graph that shares a node with another edge. I'm investigating, why this was allowed.

**Comment by bannanc** [comment]
~I could use some help on how this is happening, 
I read through the best_mathc_reference_types method again and I don't understand how it is possible that the same reference typename (atomtype) came up twice in the scoring sequence.~ 

*** LightBulb ***

In the example above, there are two current types with the same name!
We check that the current atomtype names are not in the reference list.
We also look to see if the generated SMARTS string is in the atomtype list, but we don't check for repeat typenames in the current list. 

The two "carbon aromatic" types here have different SMARTS strings `[#6a]` and `[#6&a]`

@davidlmobley I could use some advise on how best to handle this situation. 

It turns out I think this would have been possible before, we just hadn't had this occur before.

**Comment by davidlmobley** [comment]
@bannanc - it's been a long time since I looked at the code for this, so I'm not sure I'll be that helpful from a coding point of view. But, seems like it shouldn't be possible to include the same atoms in two sets of matches unless we're not checking something we should be.

In other words, if atoms are being matched to `[#6a]` then they shouldn't be allowed to match `[#6&a]` also, right? It would only be if you had, say, `[#6ar5]` first (if I'm remembering right and that's for a five membered ring...?), then you'd be allowed to have `[#6a]` later because the latter would cover some chemical space not covered by the first. But you shouldn't be able to create types which only match things already covered by existing types, right? 

I'm probably missing something though.

**Comment by bannanc** [comment]
So the problem, in this case, comes because matches are stored by typename, not smarts string. Both types `[#6a]` and `[#6&a]` had the typename "c_carbon aromatic". 

So when we typed the atoms it only stored the last type name, c_carbon aromatic", but when matches are calculated there is a node for each atomtype so there are two nodes with the same name c_carbon aromatic. Apparently this is allowed with the bipartite system. 

The solution needs to happen when the proposed typename is generated. There are two options

1. reject a move if the proposed typename is in the existing list.

2. If the proposed typename is in the existing list make a new typename for it so it's not in the list. 

@davidlmobley I hope that is clear, I come discuss it in person if not. I think option 1 above makes most sense for smarty. 

I avoided this issue in smirky by generated "type numbers" that are not allowed to match any existing types. I was under the impression the bi-partite graph would crash if it had repeating typenames, but it only complains if a typename on one side of the graph is also on the other side of the graph, apparently you can have repeating names on the first side.

**Comment by bannanc** [comment]
Ok, I realized what is probably happening with the bipartite graph is that there is one node with the "carbon aromatic" name, but because we loop through the list of atomtypes we find that same node twice.

**Comment by bannanc** [comment]
New typename generation in pull request #212
