### ISSUE TITLE
HasAlpha method won't work correctly if you use replacements

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#213]
Something I noticed when updating the smarty documentation was the way we check for Alpha atoms won't work if there are substitution strings. 

The `HasAlpha(atomtype)` method is supposed to return true if an atom has an alpha substituent. 
It does this by checking for a '$' symbol. 
Thus far, we have not used replacement options when using the combinatorial-decorators option. 
So the only time a '$' appears is when an alpha substituent is added, such as [#1] --> [#1$(*~[#6])]. 
While we might not be testing smarty with replacements, we present it as an option, for example you
could include [$halogen] in your initial types with the line
```
[#9,#17,#35,#53]    halogen
```
in your substitution file. 
In that case if you called `HasAlph( ("[$halogen]", 'halogen') )` it would return `True`

I propose we instead look for the sub string `$(*` since those are the actual set of characters you need in a SMARTS string to write a alpha substituent. This is what I am going to include in pull request #212

**Comment by bannanc** [comment]
@davidlmobley heads up ^

**Comment by davidlmobley** [comment]
Yes, this would be a substantial improvement, @bannanc .

**Comment by bannanc** [comment]
fixed in pull request #212
