### ISSUE TITLE
MiniDrugBank atoms still not typed? 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#215]
There seems to be an issue with atomtypes in the MiniDrugBank set, still...

Here is a section from the command line output for a sampling of hydrogen:
```
PROPOSED:
Atom type matches:
c_hydrogen                                                       matches        H :     5309 atoms matched
5309 / 5309 total atoms match (100.000 %)
Iteration 0 / 10000
Attempting to create new subtype: '[#1]' (c_hydrogen) -> '[#1$(*~[#15])]' (c_hydrogen any c_phosphorous )
Atom type '[#1$(*~[#15])]' (c_hydrogen any c_phosphorous ) unused in dataset; rejecting.
Rejected.
INDEX        ATOMS  MOLECULES                                                          TYPE NAME                           SMARTS REF TYPE        FRACTION OF REF TYPED MOLECULES MATCHED
    1 :       5309        254 |                                                       c_hydrogen                             [#1]        H             5309 /             5309 (100.000%)
TOTAL :       5309        259 |                                                                                                        5309 /     5309 match (100.000 %)
```

It seems to think there is only one atomtype for all hydrogen atoms, H, but there were 13 hydrogen types when I created the MiniDrugBank molecule set last week. 

I think there may have been a flavor/format issue when I saved the MiniDrugBank output file, I'm looking into it right now. (heads up @davidlmobley )

**Comment by davidlmobley** [comment]
Yes, I think I had some issues in the past with atom types not getting preserved on filtering. The filtering tool might need some adjustment on that front.

**Comment by bannanc** [comment]
I thought I had taken care of it, but I guess not. 
I've followed the AlkEthOH structure instead and made two mol2 files, one with parm@Frosst types and one with Tripos. (I'm not sure we need the Tripos types, but I have the files now...)

I'll get a pull request in the morning with them in the data/molecules/directory

**Comment by bannanc** [comment]
This was fixed a while ago and the most recent version also has the correct atomtypes.
