### ISSUE TITLE
Switch to main OpenEye releases rather than beta channel

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#219]
We should switch back to the release channel for OpenEye toolkits rather than the beta; the beta will sporadically be unavailable for specific architectures (for example, see #218 ).

**Comment by bannanc** [comment]
@davidlmobley Did you cover this? I think it was included in pull request #239 ?

**Comment by davidlmobley** [comment]
Looks like no: https://github.com/open-forcefield-group/smarty/blob/3dfce4f789e1f1eecb4fd59f4f08bcdb014a69c6/.travis.yml#L24

**Comment by davidlmobley** [comment]
Resolved on `openforcefield` recently; probably not necessarily to resolve here.
