### ISSUE TITLE
More problems with MiniDrugBank: repeat molecules and generic parameters

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#226]
Due to the way I was creating the MiniDrugBank mol2 files, they were accidentally appended to during the last fix, meaning there are multiple copies of the same molecule in each file. I'm going to fix the relevant ipython notebook and submit a pull request with the fixed mol2 files. (Then restart the smirky jobs I'm running)

Also, thanks to a comment David made this morning I am checking for generic parameters and there are generic parameters in the set which is something we probably don't want. I'm looking at which molecules have generic parameters and why right now.

**Comment by bannanc** [comment]
Heads up @davidlmobley

**Comment by davidlmobley** [comment]
I did see this. Thanks for catching/fixing. Keep me posted on which have generic parameters; could be I can help with quick fixes (I've done quite a bit of archaeology on the smirnoff source files before).

**Comment by bannanc** [comment]
@davidlmobley I added the missing bonds, angles, and torsions to issue #216 since that was about smirff99Frosst instead of being about the molecule set, I think some of these parameters should definitely be in smirff, but there is also some WEIRD chemistry. I can start trying to tackle these and open a new pull request.

First I'm going to remove the repeated molecules from MiniDrugBank, since that is a faster one to tackle.

**Comment by davidlmobley** [comment]
Thanks, @bannanc . I have #216 up but may run out of time (before my next meeting) before I can thoroughly digest.

**Comment by bannanc** [comment]
Closed by #231
