### ISSUE TITLE
Switch to using feature branches and a protected master

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#23]
Relocated from https://github.com/open-forcefield-group/smarty/pull/22#issuecomment-227913804
## 

Perhaps we want to move to using [feature branches of the main repo](https://bocoup.com/weblog/git-workflow-walkthrough-feature-branches) to ensure tests are run in the future?

There is a way to [do this safely](https://help.github.com/articles/about-protected-branches/) by preventing pushes to the master.

**Comment by davidlmobley** [comment]
We've already switched to using branches. I just adjusted the settings by protecting the master branch and requiring tests to pass (except for admins) before merging to master. So, I'll close this.
