### ISSUE TITLE
Convert_frcmod.py should take dates and authors from the smirffishFrcmod file

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#233]
@davidlmobley and I recently ran into an issue where I had made changes to smirff99Frosst and submitted a pull request without changing the date. I'm going to update the smirff9ish file and convert_frcmod.py to allow a user to specify the date and author list in the smirffishFrcmod file instead. 

I'll include this in pull request #232 (unless someone wants the new code submitted separately)

**Comment by davidlmobley** [comment]
Sounds good. Probably the date should automatically default to the date the script is run unless the user overrides, since the main reason to run it would be to compose a new version.

**Comment by bannanc** [comment]
> unless the user overrides

This sounds more complicated... Also if anyone checks things with the parameter_usage notebook it runs the convert script. I think its fine for it to be user specified, but having EVERYTHING that can be hand tweaked in one file will make this easier (or at least harder to forget to change the date).

**Comment by davidlmobley** [comment]
OK, sounds good, @bannanc .

**Comment by bannanc** [comment]
Included in pull request #232
