### ISSUE TITLE
Issue with SMIRKY and typing molecules 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#236]
I'm getting the following error when running SMIRKY on MiniDrugBank on Bonds:

```
Traceback (most recent call last):
  File "/Users/bannanc/anaconda/bin/smirky", line 11, in <module>
    load_entry_point('smarty==0.1.5', 'console_scripts', 'smirky')()
  File "/Users/bannanc/anaconda/lib/python2.7/site-packages/smarty/cli_smirky.py", line 167, in main
    option.SMIRFF, option.temperature, output)
  File "/Users/bannanc/anaconda/lib/python2.7/site-packages/smarty/sampler_smirky.py", line 302, in __init__
    raise Exception("Reference types in SMIRFF (%s) do not type all %ss in the molecules" % (self.SMIRFF, self.typetag))
Exception: Reference types in SMIRFF (inputFiles//smirff99Frosst.ffxml) do not type all Bonds in the molecules
```

This is confusing on two fronts 
1. I chose molecules based on how smirff99Frosst types the molecules. 
2. smirff99Frosst has completely generic Bond parameters so it should never fail this part. 

The part of the code raising an error uses all indices that are typed by a generic bond `[*:1]~[*:2]` (or whatever parameter is being sampled) then makes sure each of those indices tuples are assigned a parameter by a given parameter set. 

I've been trying to find what is causing this error for most of the day today, and have yet to find where the issue is. I'm working on walking through the smirky code step by step in an ipython notebook so I can see if I can identify if the problem is with the molecule set or if there is something in the smirky code that we haven't caught before now.

**Comment by bannanc** [comment]
I think I've found the problem:

For references and the current list of parameters, I store a dictionary with the form:
`parameterID = typed_molecules[ SMILES ][ (Index tuple) ] `

SMIRKY also has an `IndexDictionary` that is in the same form, but has all `(Index tuple)`s that match the generic parameter (i.e. `[*:1]~[*:2]` for a bond). 

When checking if a typelist types all molecules I create the `typed_molecules` dictionary and make sure it has all the `(Index tuple)` keys that the `IndexDictionary` has. 

In the section that causes the problem above,  I create a "typelist" with the following line:
` reference_types = [[smirks, pid] for pid, smirks in reference_typename_dict.items()]` 
This takes the reference SMIRKS and PID's out of the order they were in the smirff.ffxml. 

@davidlmobley The forcefield tools throw an error if the ffxml file can't type a molecule right? So I think this is an overly redundant check anyway.

**Comment by bannanc** [comment]
If I comment out [lines 301-302](https://github.com/open-forcefield-group/smarty/blob/master/smarty/sampler_smirky.py#L301) in sampler_smirky.py everything runs just fine. 

I'm going to rewrite the reference check to not use the `check_typed_molecules` method which was written with the "current types" in mind. I'll get a pull request in soon.

**Comment by davidlmobley** [comment]
@bannanc :

> The forcefield tools throw an error if the ffxml file can't type a molecule right? So I think this is an overly redundant check anyway.

Yes, it should be that anything which gets no parameter (NOT something which get generic parameters, though) fails... 

Glad you found the problem!!

**Comment by bannanc** [comment]
@davidlmobley 
> Yes, it should be that anything which gets no parameter (NOT something which get generic parameters, though) fails...

That's what I thought, I'm adding a slightly different check just incase, I'm testing it now, I'll have a pull request in soon.

**Comment by bannanc** [comment]
This was fixed a while ago.
