### ISSUE TITLE
Turn on zenodo for this repo

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#240]
I seem not to have turned on Zenodo for this repo yet and updated the README.md with the associated DOIs; will need to do so.

**Comment by jchodera** [comment]
Seems to be working now!
[![DOI](https://zenodo.org/badge/60921138.svg)](https://zenodo.org/badge/latestdoi/60921138)

**Comment by jchodera** [comment]
I've added a Zenodo DOI badge in #242
