### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#243]
We currently have 26 open branches:

https://github.com/open-forcefield-group/smarty/branches

Might be good to clean up some stale ones.

**Comment by bannanc** [comment]
I've done this for smarty, we now have three (master, mine, and Camila's). I'm going to close this issue.

**Comment by bannanc** [comment]
I'm not migrating this issue, if the same thing needs to happen in other repos we can make that judgement call.
