### ISSUE TITLE
Remove SMIRFF/SMIRNOFF and ChemicalEnvironment remnants from this repo

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#244]
We've now migrated the SMIRNOFF forcefield to a new repo:

http://github.com/open-forcefield-group/smirnoff

I was able to preserve commit history on all files that made the transition, though renaming `smarty` to `smirnoff` makes it harder to view this history in github.

Once that is stable, we should remove SMIRNOFF from this repo.

**Comment by davidlmobley** [comment]
Excellent, thanks, @jchodera !!

**Comment by jchodera** [comment]
Let's hold on this until I update the new repo according to our slack discussion.

**Comment by jchodera** [comment]
I have completed the bulk of the reorganization in https://github.com/open-forcefield-group/openforcefield. Please go there and comment/contribute PRs!

**Comment by jchodera** [comment]
We have now completed the migration to http://github.com/open-forcefield-group/openforcefield, so should remove SMIRNOFF and ChemicalEnvironment from this repo.

**Comment by davidlmobley** [comment]
Agreed. Just haven't had the time to do anything about it - still catching up after last week.

**Comment by bannanc** [comment]
I have this working on my local machine. I'm working on changing the travis settings so the tests on github will work. 
See pull request #250

**Comment by davidlmobley** [comment]
Thanks, @bannanc .

**Comment by bannanc** [comment]
This was fixed in [openforcefield PR#7](https://github.com/open-forcefield-group/openforcefield/pull/7)
