### ISSUE TITLE
isinstance for file doesn't work in python3

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#252]
I tried running smirky on my desktop for the first time today since switching to python3.5. 

I get this error when calling smirky:
```
Traceback (most recent call last):
  File "/Users/bannanc/anaconda3/bin/smirky", line 11, in <module>
    load_entry_point('smarty==0.1.6', 'console_scripts', 'smirky')()
  File "/Users/bannanc/anaconda3/lib/python3.5/site-packages/smarty/cli_smirky.py", line 138, in main
    atom_OR_bases = smarty.parse_odds_file(option.atom_OR_bases, verbose)
  File "/Users/bannanc/anaconda3/lib/python3.5/site-packages/smarty/utils.py", line 77, in parse_odds_file
    if isinstance(filename, file):
NameError: name 'file' is not defined
```

The utils function to parse_odds_file is allowed to take a string or a file object. 

If I run the tests they work, they all pass. The smirky sampler tests do use the parse_odds_file function.  However, if I interactively load the smarty utils function and try to load an odds file I get an error. 
I did some googling and it appears that python3 doesn't support the file type you should instead use:

```python
from io import IOBase

if isinstance(file_object, IOBase):
```

I wrote the parse_odds_file function and I thought I copied this isinstance from another method somewhere, but now I can't find it in smarty or openforcefield. 

@davidlmobley do you have any idea why the tests would pass when this function doesn't work in other places?

**Comment by davidlmobley** [comment]
@bannanc : superficially it looks like the code you're looking at is just related to printing of debug information:
```python
if verbose:
        if isinstance(filename, file):
            print("Attempting to parse file '%s'" % filename.name)
        else:
            print("Attempting to parse file '%s'" % filename)
```
and the tests run with `verbose = False` so this is skipped.

**Comment by bannanc** [comment]
Oh, thank you @davidlmobley I should have seen that! 

I think we should change two things 
1. I don't think the extra if verbose section that the top is necessary
2. Even so, we should probably be running at least 1 test with verbose = True just in case there are other places where this sort of thing comes up.

**Comment by davidlmobley** [comment]
SGTM.

**Comment by bannanc** [comment]
in PR #254
