### ISSUE TITLE
Remove `The-SMIRFF-force-field-format.md` 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#255]
[`The-SMIRFF-force-field-format.md`](https://github.com/open-forcefield-group/smarty/blob/master/The-SMIRFF-force-field-format.md) is still in this repository. The updated version for SMIRNOFF is in openforcefield so I think we should remove the duplicate file.

**Comment by davidlmobley** [comment]
Yes, please.

**Comment by bannanc** [comment]
I did this in my last PR, closing.
