### ISSUE TITLE
Fix incomplete SMIRFF ffxml file

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#28]
See https://github.com/open-forcefield-group/smarty/pull/24#issuecomment-229530731

To be done in Mobley lab. Most likely @bannanc or myself. Just requires typing/reformatting a few lines.

**Comment by bannanc** [comment]
I'll fix this in the afternoon tomorrow, it should be a very fast fix.

**Comment by bannanc** [comment]
I want to make sure I understand what the smirff string is saying so I can add the carbons and oxygens to the lennard jones section. 

At the end of the smarts string there is a :number for example [#1:1] then in bonds it has things like [#6X4:1]-[#1:2] 
I assume the this number is counting the atom number in the fragment? 
So for any atom in the lennard jones section there should be a :1 at the end? 

@davidlmobley let me know if that makes sense if you know.

**Comment by jchodera** [comment]
You have to tag _the atom to which the LJ term should be assigned_ with `:1`.

**Comment by jchodera** [comment]
For example, `[#1][#7:1]([#1])[#6]` would mean that the nitrogen (`#7`) gets the Lennard-Jones assignment.

**Comment by bannanc** [comment]
Thanks @jchodera 
that makes more sense

**Comment by davidlmobley** [comment]
Closed by #30
