### ISSUE TITLE
Implement IDIVF FFXML tag for AMBER-compatibility

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#41]
As discussed here, https://github.com/open-forcefield-group/smarty/pull/38#issuecomment-230359440 AMBER has an IDIVF flag for torsions, which is the first torsional parameter on each line in the SMIRFF mockup Christopher Bayly put together: https://github.com/open-forcefield-group/open-forcefield-data/blob/master/Model-Systems/SMIRFF_prototype/smarff_mockup1.Frosst_AlkEthOH

This got dropped on switching from the mockup to XML format, where only three parameters are provided per torsion rather than the four which were in the mockup: https://github.com/open-forcefield-group/smarty/blob/master/smarty/data/forcefield/Frosst_AlkEtOH.ffxml

I think the solution is to add an **optional** IDIVF flag for **proper torsions only** (per AMBER format); if present, then the barrier height would get divided by IDIVF, AMBER-style, and if not present, the barrier height would be handled normally.

**Comment by davidlmobley** [comment]
This will resolve part of #38 .

**Comment by jchodera** [comment]
Addressed by #43
