### ISSUE TITLE
Add suitable keyword for Smirff trefoil SMARTS impropers

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#51]
SMIRFF will use improper torsions which involve a trefoil-type SMIRKS pattern. The plan is to apply these to all (three? six? Bayly thinks 6) paths which constitute an improper to avoid problems with ordering/ambiguity.

We need to add a suitable keyword for specifying these to SMIRFF.

Not high priority yet.

**Comment by jchodera** [comment]
How about a `symmetrize="True"` keyword to symmetrize the impropers?

**Comment by davidlmobley** [comment]
Sounds perfect to me.

**Comment by cbayly13** [comment]
Do we need a keyword beyond simply the parameter type of "Improper"? When would we not be symmetrizing?
BTW there are 6 impropers around a trefoil.

**Comment by jchodera** [comment]
> Do we need a keyword beyond simply the parameter type of "Improper"? When would we not be symmetrizing? BTW there are 6 impropers around a trefoil.

I don't believe the current behavior of `tleap` includes all 6 impropers around a trefoil, so if we want to match the behavior of other codes for validation or reproducibility reasons, we would need a way to select the behavior mode.

I'm all in favor of having the default mode be the "good" behavior, but providing a compatibility mode (e.g. `mode="amber"`) for backward-compatibility with other codes.

**Comment by davidlmobley** [comment]
Yes, I totally agree with @jchodera here. We don't want to put ourselves in a world where we couldn't implement something similar to AMBER, CHARMM, etc. as a SMIRFF if we wanted to. 

Specifically, if we made it so all impropers were this way it seems possible that it it might make it impossible to reproduce parm@frosst energies on the full ZINC set. So we should retain the possibility of having old-style behavior if and when we want it.

**Comment by cbayly13** [comment]
_Sigh_ I suppose we do have to reproduce the old flawed way of doing things.

**Comment by jchodera** [comment]
OK, which behavior do we want?
- Default to adding all 6 trefoil impropers, obtain old behavior with a keyword (which one?)
- Default to adding one improper, add all 6 trefoil impropers if a keyword is specified (which one?)
- Require keyword to be specified so behavior is unambiguous

Note that even if we add just one improper, we probably won't add the same improper that `tleap` is adding, so as @cbayly13 has pointed out before, we have to be careful to separate impropers in the energy component validation checks because these will not be the same.

**Comment by davidlmobley** [comment]
Require `symmetrize = True` or `symmetrize = False` is my take so it's unambiguous. In the force fields we make, we're goign to be using `symmetrize = True` but we need the old one for reproducibility purposes.

**Comment by jchodera** [comment]
Last question: For symmetrize = True, do we divide the barrier height by 6 and then apply it to all six impropers, of do we just apply it six times?

**Comment by davidlmobley** [comment]
Let's just say we'll apply it six times. Since at this point we have no parameters, this will just get built into our parameter choices, right? Applying it six times seems simpler to me.

**Comment by jchodera** [comment]
The downside of that approach is that the barrier heights for those two
schemes will be totally incompatible. You would have to divide all the k
values by 6.0 in order to translate them.

**Comment by davidlmobley** [comment]
Ah, well, in that case maybe we should do it the other way. Since we're going to be learning the forcefields here, there's really no reason to really prefer one over the other other than for backwards compatibility with existing forcefields as you point out.

**Comment by davidlmobley** [comment]
I've just run up agains this issue again in energy validation, but it's actually unclear to me that we can do anything useful at all here with `symmetrize = False` since (a) our SMIRKS patterns will match all paths anyway, so if we only apply this to one of them we're going to end up with something totally arbitrary, and (b) as John noted, that arbitrary thing almost certainly won't match AMBER.

Given where things ended up (somewhat ditching AMBER anyway in favor of Christopher's hand-coded smirff99Frosst implementation), at this point I'm just leaning towards dividing the barrier heights by six and maintaining symmetrization always, without any attempt at backwards-compatibility with AMBER. 

I think if someone wants to add the backwards compatibility later, they could add `symmetrize = False` as an optional argument and come up with a way to implement this that isn't arbitrary or which mimics the arbitrariness AMBER uses.

**Comment by davidlmobley** [comment]
@jchodera - quick question. Do you have any preferences as to whether division by a factor of six is implemented inside `ForceField` versus required in the file? I'm somewhat leaning towards doing it internally in `ForceField` since (a) dividing current barriers for impropers, such as `1.0`, by a factor of six will tend to lead to unsightly rounding in the ffxml files, and (b) it will allow more direct visual comparison with AMBER formats. 

This won't be an issue once we begin fitting forcefields to energetic data, etc., so it's not of major significance. But, I have to deal with it to finish testing impropers so it'd be nice to know if you have a preference.

**Comment by jchodera** [comment]
I'm fine with making the sensible behavior (divide by six and apply to all torsions in the trefoil) be the default, and later adding support for backwards-compatibility if we figure out how to do so.

**Comment by davidlmobley** [comment]
Closed by #143
