### ISSUE TITLE
"Use cases" field in SMIRFF xml?

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#65]
Discussion: Chris Bayly suggested we include a "use_case" field in the ffxml files which would give a simple example SMILES for a fragment in which the specified parameter would be used, just to make it easier for people to be able to see what parameters are intended to cover. Thoughts?

**Comment by jchodera** [comment]
If your goal is to annotate handwritten XML files, why not use XML comments?

You can certainly add additional attributes like this if you want, but they
will be ignored by the ForceField parser.

In summary: Do what makes you happy to the manually curated XML files! It
shouldn't break anything.

**Comment by davidlmobley** [comment]
Yes, understood. 

Having them as a tag might make sense from the standpoint of being able to make nice visualizations of what the parameters are supposed to be doing downstream; comments are less helpful for this since they aren't automatically parseable as easily.

This issue is mostly here to remind me to discuss it with Christopher when he gets back to see if he has a specific use case in mind.

**Comment by jchodera** [comment]
The important question for me is this: if you want the sampling framework
to generate these, how would it do that, and does it offer added value over
just having a tool that finds matches in a set of molecules to display in
some useful way?

**Comment by davidlmobley** [comment]
Exactly. I'll discuss that with him when he gets back (looks like about a week from today).

**Comment by davidlmobley** [comment]
I'm closing this -- I think the functionality needed is just to query a set of molecules and see which match the specified string, which is trivial.
