### ISSUE TITLE
Is there a way to store descriptive info with OpenMM forces?

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#66]
Previously, Christopher Bayly had requested that we track parameter ID numbers (serial numbers, basically) and parent IDs in the SMIRFF format, i.e. his original mockup had something like this:

```
[#6X4]-[#6X4]    parBond  (1.526, 310.0) parNum b001 {CT-CT from frcmod.Frosst_AlkEthOH}
[#6X4]-[#1]      parBond  (1.090, 340.0) parNum b002 {CT-H_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H1] parBond  (1.410, 320.0) parNum b003 {CT-OH from frcmod.Frosst_AlkEthOH}
[#6X4]-[O&X2&H0] parBond  (1.370, 320.0) parNum b004 {CT-OS from frcmod.Frosst_AlkEthOH}
[#8X2]-[#1]      parBond  (0.960, 553.0) parNum b005 {OH-HO from frcmod.Frosst_AlkEthOH}

# angles
[a,A]-[#6X4]-[a,A]   parAng (109.50, 50.0) parNum a001 {consensus matches all X-Csp3-X}
[#1]-[#6X4]-[#1]     parAng (109.50, 35.0) parNum a002 {H1-CT-H1 from frcmod.Frosst_AlkEthOH}
[#6X4]-[#6X4]-[#6X4] parAng (109.50, 40.0) parNum a003 {CT-CT-CT from frcmod.Frosst_AlkEthOH}
[#8X2]-[#6X4]-[#8X2] parAng (109.50, 70.0) parNum a004 {O_-CT-O_ from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#1]   parAng (108.50, 55.0) parNum a005 {CT-OH-HO from frcmod.Frosst_AlkEthOH}
[#6X4]-[#8X2]-[#6X4] parAng (109.50, 60.0) parNum a006 {CT-OS-CT from frcmod.Frosst_AlkEthOH}

# torsions
[a,A]-[#6X4]-[#6X4]-[a,A]   parTor ( (9, 1.40, 0.0, 3) ) parNum t0001 {X -CT-CT-X from frcmod.Frosst_AlkEthOH}
...
```

And he subsequently added a request for tracking also `parent_id` for each parameter.

This can trivially be added to the SMIRFF XML format by just adding new tags `parameter_id` and `parent_id` or some such, HOWEVER, this info also won't be retained or used in any way. What would be ideal would be to be able to track it internally in OpenMM, i.e. a `Force` for a specified torsion would be tagged with its parameter number at least. This would greatly aid debugging like the work I did recently where I'd encounter a force/energy inconsistency between two different setups of the same system and I'd need to track down why it was there. Currently, if I get a differing forces applied to a set of atoms in an OpenMM system/simulation, I have access to the atom numbers, the force term, and the parameters applied, but there is no mechanism to tell where the parameters came from so I have to figure this out by inference.

So, my question is this: **Is there a mechanism to store descriptive info to an OpenMM Force term**, such as a parameter_id corresponding to the parameters used for that force? I've been looking at the docs and as far as I can tell the answer is "no", but I figured it was worth asking.

If the answer is "no", then presumably if we do add `parameter_id` to the XML files we can only use this while parsing the files but then we'll lose it thereafter, unless we do something which creates some sort of a lookup table of which force terms came from which parameters... 

There's not a huge functional importance to this at present, though it likely will continue to be something that would be helpful in debugging in the future.

**Comment by jchodera** [comment]
> So, my question is this: _Is there a mechanism to store descriptive info
> to an OpenMM Force term_,

Nope.

We can certainly create a mechanism to track this information in an object
that mirrors System and its Force objects, but it would be critical to
first understand how you want to use this information. Can you come up with
specific ways you would want to access and use this information, and how
you would dream up coding with that mechanism available?

**Comment by davidlmobley** [comment]
Just to be clear, this is very low priority:

> We can certainly create a mechanism to track this information in an object
> that mirrors System and its Force objects, but it would be critical to
> first understand how you want to use this information. Can you come up with
> specific ways you would want to access and use this information, and how
> you would dream up coding with that mechanism available?

The two most immediate examples would be things like here https://github.com/choderalab/openmoltools/blob/master/openmoltools/system_checker.py#L254 and here https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield_utils.py#L189 where one would print not just what torsions are different or are found, but what parameter IDs the values came from. i.e., in addition to:

``` python
i0, i1, i2, i3, per, phase, k0 = force.getTorsionParameters(k)
```

having

``` python
param_id = force.getTorsionID(k)
```

for a subsequent print of `param_id`.

I'm not stuck on that specific implementation of course, but right now there is no way to recover the origin of the specific parameters.  

(This would have saved me HOURS in debugging the AlkEthOH energies; right now there is no way to backtrack from knowing that a specific torsion has a different energy in some system to figuring out what parameter specified that energy. This gets increasingly more nontrivial the more parameters there are in a SMIRFF file given the hierarchical nature of it. For AlkEthOH, I could handle the hierarchy by hand by just starting at the bottom and working my way up through SMIRKS matches until I found one which matched the set of atoms in question, but for larger parameter files this would quickly become impossible.)

I realize these examples are only in the context of "checking to see whether energies which should match actually do match", which is only something we're doing temporarily. Still, as soon as we are doing sampling over SMIRKS while parameterizing to data, we're probably going to run into situations where we want to know which SMIRKS pattern and parameters are responsible for a particular property we're measuring (a bond distance, for example) so being able to work backwards from the force terms to figure out which lines/parameter IDs from the SMIRFF parameter set were responsible for those parameters/force terms will be very helpful.

**Comment by davidlmobley** [comment]
The answer to this was "no", so #82 added a structure to easily query which parameters would be used by a specific molecule.
