### ISSUE TITLE
Outline python representation of SMIRFF parameters for manipulation

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#68]
Soon, we will move to proposing moves in parameter space, such as:
- modifying existing parameters from a SMIRFF file
- adding new parameters (and SMIRKS string) that are descendants of old parameters

Currently, the only way to do this is to work directly with the XML or a representation thereof. It may be more convenient to have an internal Python representation of the parameters to work with. This issue is so that we (on the Mobley lab end) lay out how this would work. What would we want it to do?

For example, perhaps we want to be able to iterate over bonds, angles, torsions, vdW types, modify specific parameters for specified types, or create child parameters which have modified but related parameters. 

Since we are also moving to having parameter numbers labeling each parameter, along with tracking parent parameter ID's, presumably this representation would also understand those in order to make it easy to know what parameter numbers to assign to new parameters which are introduced.

Perhaps there is inspiration that can be drawn from ParmEd here.

Perhaps this also can be combined with the coloring issues we are looking at in Smarty - i.e. perhaps it could be made easy to use this representation to see which atoms in which molecules in a specified set are "colored by" (parameterized by) a particular parameter, such as in https://github.com/open-forcefield-group/open-forcefield-tools/issues/5. Or, for example, making it easy to access all instances of a particular parameter in all molecules in a specified set, or all parameter IDs used in a particular molecule, as per https://github.com/open-forcefield-group/open-forcefield-tools/issues/4.

We'll need to take some time to think through this and I'll probably need to discuss with Christopher as well.

**Comment by davidlmobley** [comment]
It is possible there is a way that I don't understand that this could also help address the issue raised in https://github.com/open-forcefield-group/smarty/issues/66 about making it so it's easy to take a specific force term from an OpenMM system and see what parameters it came from -- though if there's a connection it's not obvious to me.

**Comment by davidlmobley** [comment]
@bannanc - would probably be useful to have your thoughts on this when you have time.

**Comment by bmanubay** [comment]
One thing that I just discussed with @davidlmobley, mainly for the purpose of testing uncertainties of energies calculated from different movements in parameter space (see: https://github.com/open-forcefield-group/open-forcefield-tools/issues/19#event-730664993) would be the possibility of reading in parameters as an array object into Python, so that they can be easily edited in a script. For now, it looks like I'm going to have to edit the ffxml files directly in order to change those parameters and sample in that space. 

It would be nice to be able to pull those initial parameters from the starting ffxml (indexed with a particular bond pair, angle trio, or torsion quartet of atoms) and be able to store them as an array. I would want to be able to take those changes and directly apply them to the forcefield in order to re-assess the energies.

**Comment by jchodera** [comment]
There are a lot of infrastructure requirements necessary for doing that.
ParmEd does this rather well, but has a lot of complexity as a result.
Manipulating XML objects is not incredibly difficult with lxml. What do we
really want to simplify, and what does that mean for the object model we
want to use?

**Comment by davidlmobley** [comment]
@bmanubay :

> It would be nice to be able to pull those initial parameters from the starting ffxml (indexed with a particular bond pair, angle trio, or torsion quartet of atoms) and be able to store them as an array.

Can you give an example of how you would imagine this working? For example, would you want to say something like:
`parameters['NonbondedForce']['[#1:1]'].rmin_half = 1.50`

Maybe a setter/getter notation is preferable, i.e. via `set_rmin_half(1.5)` and `get_rmin_half()` (alternatively, `set_sigma(value)` and `get_sigma()`. Also, it's unclear to me whether the SMIRKS should be arguments. Hmm.

@jchodera :

> There are a lot of infrastructure requirements necessary for doing that.
> ParmEd does this rather well, but has a lot of complexity as a result.
> Manipulating XML objects is not incredibly difficult with lxml. What do we
> really want to simplify, and what does that mean for the object model we
> want to use?

Seems like some of the major things that are going to be not particularly convenient right now are:
- Find a parent SMIRKS and create a child SMIRKS which has a unique parameter ID and related but different parameters
- hmm, most other things don't seem that terrible

But as you note, maybe this takes us too much into the land of "let's find a general way of representing parameters internally" so maybe we should just be implementing simple functions to do the major tasks we need via XML libraries. 

Probably a **short term solution which can easily be generalized** is to just make a `forcefield_data` container or something like that which has getters and setters to interact with specific types of data/parameters; initially the data would just be stored AS XML via the XML library `forcefield.py` currently uses. These can be functions which interact with the XML via an XML library initially, then if we see the need we can swap out the "interact with the XML directly" for an "interact with a python representation of the parameters".

**Comment by bmanubay** [comment]
@davidlmobley I guess my vote would be for a getter/setter notation, but the question comes to mind, how is the best way to specify the force and SMIRKS identifiers we're interested in?

Like:

`parameters['NonbondedForce']['[#1:1]'] = set_rmin_half(1.50)`

?

That seems like a good place to start from as far as I can tell.

**Comment by davidlmobley** [comment]
> how is the best way to specify the force and SMIRKS identifiers we're interested in?

@bmanubay - I don't quite understand the question.

**Comment by bmanubay** [comment]
Maybe I phrased this poorly or have some misunderstanding. 

There needs to be a general way to represent the force (ie, `HarmonicBondForce` or `NonbondedForce`) and the part of molecule (or the SMIRKS representation) we're interested in applying the change in parameter to (ie, `'[#1:1]'`; I think this is part of a SMIRKS string, right?). 

I'm mainly saying that the way you indicated doing so above seems good to me :)

**Comment by davidlmobley** [comment]
> There needs to be a general way to represent the force (ie, HarmonicBondForce or NonbondedForce) and the part of molecule (or the SMIRKS representation) we're interested in applying the change in parameter to (ie, '[#1:1]'; I think this is part of a SMIRKS string, right?).

Ah, yes, that's right. In the XML each force type has a particular name, such as `HarmonicBondForce`, and specific SMIRKS patterns denote specific force terms. So yes, whether you use the XML directly or work with some representation of it you'll have to specify what type of parameter you want to modify and the SMIRKS pattern. The two together denote some specific line in the file, basically.

**Comment by bannanc** [comment]
@davidlmobley 
I'm trying to catch with everything here and in the associated issues/pull requests. 

I'm a little confused about why you need to use the SMIRKS strings to access parameters. I thought part of the point of assigning parameter numbers was to make accessing parameter data easier. Why would you want to access data from the SMIRKS string?

**Comment by davidlmobley** [comment]
> I'm a little confused about why you need to use the SMIRKS strings to access parameters. I thought part of the point of assigning parameter numbers was to make accessing parameter data easier. Why would you want to access data from the SMIRKS string?

Mostly, the idea here would be an interface to make it easy to manipulate parameters via whatever means. Yes, parameter ID's now that they are there will actually probably be the most direct way to access.

**Comment by davidlmobley** [comment]
Marking as closed as we're NOT doing this now, will just work directly on XML for the time being. Will have separate issue/PR for that.

**Comment by jchodera** [comment]
For now, the easiest way to manipulate parameters is to use the `lxml.etree` representation of the XML file. You can read more about this here: http://lxml.de/tutorial.html#using-xpath-to-find-text

This will easily allow you to, for example:
- make a list of all bond types in the `HarmonicBondForce` section
- modify a parameter for one of the types
- insert/delete a type
- write out a modified XML file

**Comment by jchodera** [comment]
> Probably a short term solution which can easily be generalized is to just make a forcefield_data container or something like that which has getters and setters to interact with specific types of data/parameters; initially the data would just be stored AS XML via the XML library forcefield.py currently uses.

This is a great longer-term plan, but isn't needed at the moment. Essentially, you need to have a container class representation of the forcefield.

Would very much suggest sticking with XML for now but let's eventually decide on an API for this representation. It could either be part of `ForceField` or a separate object.

**Comment by davidlmobley** [comment]
@jchodera - yes, I'm planning on using the `lxml.etree` library. I was reading the docs for it last night when I closed this issue.

> > Probably a short term solution which can easily be generalized is to just make a forcefield_data container or something like that which has getters and setters to interact with specific types of data/parameters; initially the data would just be stored AS XML via the XML library forcefield.py currently uses.
> > Would very much suggest sticking with XML for now but let's eventually decide on an API for this representation. It could either be part of ForceField or a separate object.

That's actually what I meant, but maybe we're talking past each other. When I wrote this I was saying I could write a very basic container that has everything in XML inside it. I'm totally on board with having everything continue to be as XML right now, I am just imagining two ways to do it, though maybe there are other options I haven't thought of.
1. Have the forcefield always be stored in a file or as a direct read from a file, and write a set of independent functions that manipulate the XML the way we need (set a specific parameter, get a specific parameter, get all of the parameter IDs, etc.)
2. Have a really basic container class, perhaps called `forcefield_data`, that just (for now) uses `lxml.etree` to parse the file, then store it; it would have member functions to write back out to a file, access/manipulate specific parameters, etc.  

The second seems cleaner to me since it ties the functions to the data they are manipulating in a sensible way. But both of these are working directly on the XML using `lxml.etree`, and functionally there doesn't seem to be much difference (other than that the second could also be extended later to represent the data internally in some other format aside from XML if we needed to, without necessarily changing the API). 

Are you envisioning a third option, or saying that you prefer option 1 over option 2?

**Comment by jchodera** [comment]
I am recommending neither option, actually. `smarty.ForceField` essentially implements (1) already---the forcefield is stored in XML---though no methods have yet been added to let you manipulate the forcefield. We may simply want to add these methods to `ForceField`, rather than have a weird separation between `ForceField` and `forcefield_data`.

**Comment by davidlmobley** [comment]
@jchodera - I don't think that's accurate actually. Specifically:

> smarty.ForceField essentially implements (1) already---the forcefield is stored in XML---though no methods have yet been added to let you manipulate the forcefield.

By my reading, it is **not** stored in XML.  `smarty.ForceField` applies `loadFile` with the constructor, and `loadFile` uses the parsers to actually parse the forcefield, at which point the XML is discarded (`ForceField` does not retain it, it's only used within the `loadFile` method). Also, at present there is no way to retain things like parameter IDs when this happens, and the XML is NOT retained.

This means that I'm unsure how you would imagine this working. Being able to work with the XML within `smarty.ForceField` seems like it would involve a major rewrite. Can you elaborate on what you're thinking? 

With the current `smarty.ForceField`, it looks like manipulating parameters would involve manipulating the `force` terms which are stored, which is **not manipulating XML** as you're advocating. It's perhaps viable, but it does sound more complicated (i.e. we'd have to write methods to be able to turn the force terms back into XML, or revise the whole thing so it retains the existing XML rather than discarding it).

**Comment by davidlmobley** [comment]
@jchodera - maybe I see how this could be done without much work. I suppose `loadFile` could store the XML trees to `ForceField` rather than just discarding them as it does now, then that would allow us to add member functions which would manipulate the parameters in `trees`, and then we'd need a new method that would do a similar thing to `loadFile` (parse XML and store force terms) but using the internal trees which contain modified parameters. Is that what you're thinking?

**Comment by jchodera** [comment]
`smarty.ForceField` stores an object tree representation of the forcefield as an `lxml.etree`. You can easily write this back out to XML if you want. It's just an internal object representation---much like the one you were proposing to write---that can be manipulated, albeit the API is more general (and less specialized to forcefield operations).

**Comment by davidlmobley** [comment]
@jchodera:

> smarty.ForceField stores an object tree representation of the forcefield as an lxml.etree. You can easily write this back out to XML if you want

Not correct. Currently this is in `trees` which is a local variable which only exists within the `loadFile` function. Maybe that's not what you intended, but it's what you wrote.

**Comment by davidlmobley** [comment]
But I think I see what you're saying, @jchodera - make sure to read this comment which I posted while you were writing. https://github.com/open-forcefield-group/smarty/issues/68#issuecomment-236378604

**Comment by jchodera** [comment]
Ah, you're right---the registered forces parse the XML file and then discard it. Good point.

We could easily switch this around and have the forces regenerate from the `etree` as `createSystem` is called, if we wanted to do this (with a little loss in speed). Or you can just manipulate the XML file directly as an `etree` outside of `ForceField`.

**Comment by davidlmobley** [comment]
> We could easily switch this around and have the forces regenerate from the etree as createSystem is called, if we wanted to do this (with a little loss in speed). Or you can just manipulate the XML file directly as an etree outside of ForceField.

I'm on board with this -- I can see how it would make a lot of sense to make the parameter manipulation be tied to `ForceField`, I just couldn't figure out how to get it to fit with how ForceField currently operates, hence my focus on creating a separate set of tools which would do this.

I can write the parameter manipulation part, but could you either (a) quickly switch it around as you just described, or (b) outline the easiest way to switch it around? Would it be to just apply the parsers/generators in `createSystem` rather than `loadFile`?

**Comment by davidlmobley** [comment]
> Or you can just manipulate the XML file directly as an etree outside of ForceField.

That's what I was originally saying, but I agree that it would be preferable to be able to do this on a ForceField object, so if the necessary revisions are easy we should probably go that route.

**Comment by jchodera** [comment]
Another important question as we think about whether to keep the current `ForceField` and `ForceFieldData` separate or together: Do you envision writing out parameters for tools besides OpenMM? If so, there may be advantages to having a separate (1) container/XML interface and a (2) parameter writing thing.

**Comment by davidlmobley** [comment]
> Do you envision writing out parameters for tools besides OpenMM? 

No. We're all in for OpenMM. I figure if someone wants to use the parameters somewhere else, that is their job (or they take parameterized OpenMM systems from us and convert).

**Comment by davidlmobley** [comment]
If there is more to discuss, should we talk verbally for a moment?

**Comment by davidlmobley** [comment]
Discussion on Slack arrived at this point: The disadvantage of moving the XML parsing to `createSystem` is that we'll take a speed hit if we want to parameterize thousands of molecules since we have to parse again and again. 

The end conclusion was to:
- initially parse the XML with `loadFile` as present
- set a flag if the parameters are manipulated
- on `createSystem`, check the flag and if it has been set, re-parse the XML. 

This gives the best of both worlds, in that we get to keep the parameter manipulation tied to `ForceField` but without the speed hit. 

I'm putting this here for the record but when I get ready to work on it I'll create a separate issue.
