### ISSUE TITLE
Make ZINC parm@frosst subset for testing purposes

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#69]
After #59 , we'll be shortly^ proceeding to the parm@frosst ZINC subset rather than AlkEthOH. @camizanette reports that running on the full parm@frosst ZINC set is a bit slow, which is of course fine once we're happy with how it's running but is not ideal for testing purposes. 

We should construct a subset (perhaps randomly) of the compounds just for testing purposes. 

^ Shortly is perhaps an overstatement since some of us have already had a look at this, but when @camizanette told me she was running some tests with parm@frosst, I said, "I feel like you just told me that the next Star Wars movie came out and you had tickets for all of us but you went without us." Now that the code is available, so the rest of us can see the show now too.

**Comment by jchodera** [comment]
> @camizanette reports that running on the full parm@frosst ZINC set is a bit slow

I'd do some [profiling](https://docs.python.org/2/library/profile.html) to see if you can identify what the slow steps are. Some speed improvements might be easily identified this way.

**Comment by davidlmobley** [comment]
Totally agree that there's tons that can be done to optimize, though as you've been noting, ultimately the speed of this particular step won't be that important. For debugging purposes it will be helpful to be able to look at a subset which has chemical diversity like the full set but is just smaller.

**Comment by davidlmobley** [comment]
Made a subset of 500 molecules and now it is nice and fast. Looks like the speed is worse than linear with N -- with 7500 molecules as in the full set it looks like it'd take an hour or more to run 1000 iterations on my laptop, whereas with 500 molecules it's much much faster (a couple of orders of magnitude?). 

One can now run a more minimal parm@frosst set for testing in the relevant examples directory using:

```
smarty --basetypes=atomtypes/basetypes-elemental.smarts --initialtypes=atomtypes/basetypes-elemental.smarts --decorators=atomtypes/decorators.smarts --substitutions=atomtypes/substitutions.smarts     --molecules=molecules/zinc-subset-500-tripos.mol2.gz --reference=molecules/zinc-subset-500-parm@frosst.mol2.gz --iterations 1000 --temperature=0.0
```

or similar

(Or at least, one can once I merge #74)
