### ISSUE TITLE
Update README.md files under examples; clean out unused examples

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#79]
It came up in conversation that some of the examples are now outdated; @camizanette will be updating the README.md files therein to bring them up to date, and also:
- Removing examples which are no longer needed
- Checking the AlkEthOH tests under smarty/tests to ensure they are still current
- Removing obsolete decorator/descriptor files

**Comment by camizanette** [comment]
Working on this now.

**Comment by davidlmobley** [comment]
Closed by #81 .
