### ISSUE TITLE
Explore temperature effects on AlkEthOH

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#80]
We'll need to sort out what temperature is reasonable for us to be working at; we have to balance being able to climb out of problem minima (dead-ends) with wanting to spend most of our time exploring patterns which are likely good.

We'll look at this on AlkEthOH initially.

To do this, we should repeat many runs of smarty at each of a range of temperatures from T=0 to something that is definitely too high (T=0.2?) and look at how the max score reached each iteration, and the average score, vary as a function of temperature. 

Note, @camizanette , that max score is currently printed out so you wouldn't have to do any new analysis to get that, presumably. https://github.com/open-forcefield-group/smarty/blob/master/smarty/sampler.py#L854

**Comment by jchodera** [comment]
We should step back and ask what the goal is here.

Is the goal to obtain a perfect score? That's a global optimization
problem, and it may be very hard. Simple constant temperature Monte Carlo
is unlikely to succeed unless the problem structure is very easy---for
example, if the landscape has many paths that lead to the global optimum.

Is the goal to quantify how rugged the landscape is? In that case, you may
want to look at how often the same maximum scoring solution is recovered.

If the temperature is sufficiently high, you can even use Markov state
model techniques to understand the metastable state structure by using the
same scoring scheme to compute how close two particular parameter sets are.

Of course, this is an inherently limited toy system. We really need to be
computing some actual physical properties to see how rugged the real
landscape is (which we will be able to do very soon!).

**Comment by davidlmobley** [comment]
> We should step back and ask what the goal is here.

AlkEthOH is simple enough that I think the goal is to be able to get a perfect score a reasonable fraction of the time. I'm fairly confident that if we can't typically recover the very simple tree structure for hydrogen here (which is the problem case), that is:

```
  H
/    \
HC   HO
|
H1
|
H2
| 
H3
```

then we're really not going to be able to do anything worthwhile on real data either, as this is FAR FAR simpler than most of the types of things we're going to be trying to discover. 

Right now I think we can recover this about 50% of the time, where 50% is basically the odds of picking the right branch to explore first. I don't think that's at all satisfactory, as extrapolated over several elements which each have similar trees, this would quickly lead us down to being able to recover the right patterns roughly NEVER (i.e. if I have eight such branch points the odds of exploring the right one first for all eight would be 1/2^8 = 0.3%). 

> Is the goal to obtain a perfect score? That's a global optimization
> problem, and it may be very hard. Simple constant temperature Monte Carlo
> is unlikely to succeed unless the problem structure is very easy---for
> example, if the landscape has many paths that lead to the global optimum.

I agree that we don't necessarily want a perfect score as the landscape gets more complex, but we also want something **near enough** to a perfect score that it's somewhat credible. i.e. if you think about recovering parm@frosst atom typing as a test, it'll be somewhat acceptable if you miss some of the minor types, presumably. But if you miss ALL of the minor types, then you're basically saying you're not able to learn anything near enough chemical complexity. In other words, if half of my attempts at AlkEthOH terminate with me only discovering `HO` and `H` (generic) then I think we're learning that we're just not reliably able to discover this level of complexity, which is BAD.

But, maybe I'm missing how real data would save us in this case? Naively it seems to me like real data would just make the problem worse, because it will still be just as challenging to explore the tree of SMARTS patterns, but now we won't have anything clear-cut which says whether we're finding the environments we need. 

> Is the goal to quantify how rugged the landscape is? In that case, you may
> want to look at how often the same maximum scoring solution is recovered.

This may be a useful thing to look at, though that is not the goal here. 

> If the temperature is sufficiently high, you can even use Markov state
> model techniques to understand the metastable state structure by using the
> same scoring scheme to compute how close two particular parameter sets are.

Sorry, I'm not understanding this. What are the "parameter sets" here? Are you talking about computing how close two particular sets of SMARTS matches are or something? 

> Of course, this is an inherently limited toy system. We really need to be
> computing some actual physical properties to see how rugged the real
> landscape is (which we will be able to do very soon!).

I agree that we need to be computing physical properties soon, though I don't actually see how that will help with the SMARTS landscape issues here, other than that our scoring function will be different and potentially not as steep. Is that what you're saying?

**Comment by davidlmobley** [comment]
For now let's assume the temporary definition of success is "get to 100% at some point during our simulation or set of simulations", as this is what will allow us to:
a) be sure that we're able to generate the requisite complexity in our SMARTS patterns and demonstrate this
b) learn SMARTS patterns to generate GAFF and/or parm@frosst atom types so we can put those forcefields in SMIRFF format
c) learn how many SMARTS patterns we discover that can do (b) -- i.e. how well the types are defined/matched by SMARTS

>  Simple constant temperature Monte Carlo
> is unlikely to succeed unless the problem structure is very easy---for
> example, if the landscape has many paths that lead to the global optimum.

Going off this line of thinking - I wonder if we should be taking an approach that is a sort of analog to annealing, here. Of course one approach would be to exactly do annealing, but another approach would be to run in a couple of stages:
1. Run at high or moderate temperature to generate a range of different "starting points" (like unfolded protein structures for protein folding simulations)
2. Run at low temperature to optimize these
The idea here would be that even if we have a low likelihood of success in item 2, item 1 will give us some starting points which have a high likelihood of success

I suppose there are also a variety of other things that could be done to tinker with the likelihood of success - i.e. we could factorize the problem by element and do, say, nitrogen in one set of simulations and hydrogen in another set, so that if we have a 50% chance of success on hydrogen and a 25% chance on nitrogen we don't end up with a 1/8 chance overall, but rather still 50% and 25%. Of course this has the disadvantage that if we discover a new, useful nitrogen environment NX we can't propose a new hydrogen type which is "hydrogen connected to NX".

**Comment by jchodera** [comment]
One quick comment: We discussed earlier that there are many EQUIVALENT
trees with the same typing behavior. You are not looking to reproduce that
exact tree, right? Just an equivalent one.

**Comment by davidlmobley** [comment]
> One quick comment: We discussed earlier that there are many EQUIVALENT
> trees with the same typing behavior. You are not looking to reproduce that
> exact tree, right? Just an equivalent one.

Indeed, though in fact we so far haven't found any other trees that produce the same typing behavior.

(Please note that this is the area of the project that least needs your attention at this point, since we can keep going as is and make headway, whereas on the property calculation we desperately need you).

**Comment by bannanc** [comment]
I don't consider this an issue, we are running tests at various temperature as a way to collect data. 
These aren't things that are going to be included in the directory here. (Mostly because the resulting output is too large to track in a github repository). 

@davidlmobley - can we close this with the note that the effect of changing temperature is being discussed in the coming publication?

**Comment by davidlmobley** [comment]
So noted, @bannanc . We can probably update the `README.md` files in the relevant `examples` directories here with some conclusions about temperature effects for completeness.
