### ISSUE TITLE
Extend `ForceField` class to provide infrastructure for changing parameters

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#84]
As noted in #68 , we need to be able to make parameter moves. We'll initially do this by modifying the XML using `lxml.etree` which `ForceField` currently uses for XML handling.

Currently, `ForceField` only parses the XML on initialization and discards the XML after parsing. It will be updated to retain the XML. 

XML will still be parsed on initial reading of the file rather than on application of `createSystem` to avoid a speed hit when parameterizing large numbers of molecules if the XML is parsed when parameterizing each system. However, if parameters are modified, then a flag will be set so that the XML will be re-parsed when `createSystem` is applied.

**Comment by jchodera** [comment]
Eventually, I think you're right that we will want to operate on a Python representation (which is created from the XML parsing) directly, and also add functions to the force generators that can reconstruct an XML subtree from their own parameters so we can write an XML from the modified parameter set. But this is a great start.

**Comment by davidlmobley** [comment]
Resolved by #86 at least preliminarily.
