### ISSUE TITLE
Extra AtomTypes code in ForceField -- remove?

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#85]
@jchodera - `ForceField` currently has this code snippet involved when parsing XML files:

``` python
# Load the atom masses.
        for tree in trees:
            if tree.getroot().find('AtomTypes') is not None:
                for type in tree.getroot().find('AtomTypes').findall('Type'):
                    self.registerAtomType(type.attrib)
```

As far as I can tell, there is no functionality `registerAtomType` provided in `ForceField`, so this won't work. However, we don't currently have `AtomType` definitions in the SMIRFF format, so it doesn't trigger a failure. Should it be removed?

**Comment by jchodera** [comment]
I think I originally thought we needed to specify atom masses, but I must have ended up just using elemental integral masses instead (since fractional masses are dumb).

**Comment by jchodera** [comment]
So I think you can get rid of this, yes.

**Comment by davidlmobley** [comment]
Closing via #86
