### ISSUE TITLE
Minimum chemical environment

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#87]
Currently in the chemical environment objects we have an empty chemcial environment as the base object and then atoms, bonds, angles and torsions that build on that object. However, it seems the minimum chemical object would be an atom, you can't have a chemical environment without at least one atom. 

I think it would make more sense to change ChemicalEnvironment to AtomChemical Environment since that is the minimum size of a molecular fragment. 

@davidlmobley and @cbayly13 do you have opinions on this?

**Comment by jchodera** [comment]
What about having `AtomChemicalEnvironment`, `BondChemicalEnvironment`, `AngleChemicalEnvironment`, and `TorsionChemicalEnvironment` subclasses that start with 1, 2, 3, or 4 connected labeled atoms? `ChemicalEnvironment` can then just be an abstract base class.

**Comment by bannanc** [comment]
that is what we have now, I was just trying to understand if there was a value in having what is basically just an empty base class.

**Comment by jchodera** [comment]
If it's intended to be an abstract base class (nobody would use it directly, they'd just use subclasses), it doesn't matter. You can _prevent_ people from instantiating it directly if you want, but the danger of accidental misuse here is very little.

**Comment by davidlmobley** [comment]
Yes, I agree with @jchodera here. I don't think you need to change anything, unless you want to just change it so people don't create an instance of the abstract base class.

**Comment by bannanc** [comment]
Ok, I'll leave it as is then. The documentation in the abstract class says that it's intended to be used with the subclasses. I'll close this issue, thanks!
