### ISSUE TITLE
Implement/test normalization for scoring function

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#9]
Instead of scoring each new pattern by the number of atoms it is able to match, we want to test what happens by normalizing these so that a new pattern which matches all atoms of a given type results in a score improvement of `1.0` if it matches ALL of the atoms of that type, regardless of whether there are (to use hydrogen as an example in AlkEthOH) `68` or `244` atoms matched.

We are fairly convinced this will result in more efficient sampling in some cases, perhaps even with AlkEthOH, and it's certainly something we want to experiment with.

**Comment by davidlmobley** [comment]
As a sub-point of this, we also would want this to allow non-integer values, so that a score of `0.5` is obtained if a pattern matches half of the atoms of a given type, etc. This could be called `f` for fraction identified.

**Comment by jchodera** [comment]
> we want to test what happens by normalizing these so that a new pattern which matches all atoms of a given type results in a score improvement of 1.0 if it matches ALL of the atoms of that type, regardless of whether there are (to use hydrogen as an example in AlkEthOH) 68 or 244 atoms matched.

This _could_ be dangerous, since it rewards adding a lot of complexity for a little bit of gain.

**Comment by davidlmobley** [comment]
I think our first priority is to resolve #8 and then see how we can do. We hope to explore how things like this would impact efficiency after doing so.

I agree that it could be dangerous, though Chris is also fairly convinced it will be necessary. I guess we'll see.

I should note that right now we get stuck, even on the simple AlkEthOH, at about 81% coverage, it seems. So, right now we're not finding enough complexity. :)

**Comment by jchodera** [comment]
> I should note that right now we get stuck, even on the simple AlkEthOH, at about 81% coverage, it seems. 

Definitely try the "positive control" experiment with hand-crafted initial parameters and see if you can get 100%.

**Comment by davidlmobley** [comment]
Closing for now as we are not doing this in smarty unless it proves necessary.
