### ISSUE TITLE
Chemical environment objects should know their type

### ISSUE THREAD

**Issue by cbayly13** [open-forcefield-group/smarty#93]
Chemical environments come in four types so far: torsion, angle, bond, and improper, and have different numbers of labeled nodes and edges (atoms and bonds) that need to be randomly varied. To help know how many nodes/edges there are to randomly choose from, it would be helpful to have a method like GetType which returns an indicator for whether it is a torsion, angle, bond, or improper type of environment.

**Comment by davidlmobley** [comment]
Isn't this something one can just do using `isinstance`? See python docs:

> isinstance(object, classinfo)
> Return true if the object argument is an instance of the classinfo argument, or of a (direct, indirect or virtual) subclass thereof. Also return true if classinfo is a type object (new-style class) and object is an object of that type or of a (direct, indirect or virtual) subclass thereof. If object is not a class instance or an object of the given type, the function always returns false. If classinfo is a tuple of class or type objects (or recursively, other such tuples), return true if object is an instance of any of the classes or types. If classinfo is not a class, type, or tuple of classes, types, and such tuples, a TypeError exception is raised.

**Comment by bannanc** [comment]
I thought this might need a little more detail as to while I didn't just add the method/property. 
1. The user has the ability to add atoms to a chemical environment. They can in principle label these atoms so if you were to start with a bond and add an atom to :2 labeled :3 then you would in some sense have an angle. 
2. What form should this take, should type just be a string for each form for example "torsion" or "improper"? 

Also, there are five types, you can also make an atom.

**Comment by bannanc** [comment]
Oh, David I started writing that before I saw your comment, the only thing I would say about your comment is that currently the inheritance is a Bond inherits an Atom environment type if you had a Bond environment and you asked is instance of an AtomChemicalEnvironment would it return true since Bond is a subtype of Atom?

**Comment by davidlmobley** [comment]
Maybe, @bannanc . Also, using `isinstance` would be slightly cumbersome since one would need to check four things to figure out how many atoms one is working with. So it's probably useful to do what he asked for anyway once the additional details are ironed out.

**Comment by bannanc** [comment]
I think it's worth waiting until we have the sampler a little more put together and then we can add any useful features like this to the environment or other objects. That's why I asked Christopher to make the issue so we'll have a reference for it later.

**Comment by cbayly13** [comment]
Having made an instance of a torsion as
torsion = smirky.TorsionChemicalEnvironment()

when I run
print( isinstance( torsion, smirky.AngleChemicalEnvironment ))
print( isinstance( torsion, smirky.TorsionChemicalEnvironment ))
print( isinstance( torsion, smirky.BondChemicalEnvironment ))
it comes out True in all three cases. Is this expected?

**Comment by jchodera** [comment]
Why not just add a method to sample a random edge or atom and return that?

**Comment by cbayly13** [comment]
@jchodera : we are likely to have to sample some atoms or bonds differently from others, for example the chemical perception needed for the central bond and atoms 2 and 3 of a torsion is likely to be different from that needed for terminal atoms and bonds. To start with we will treat them the same, but I want to design in the capability to distinguish them.

**Comment by cbayly13** [comment]
@bannanc : for a putative getType() method, could we please return a string from the following set:
'None'
'Bond'
'Angle'
'Torsion'
'Improper'
'vdW'
Then I can write stuff assuming I will be able to get one of these values.

**Comment by jchodera** [comment]
> @jchodera : we are likely to have to sample some atoms or bonds differently from others, for example the chemical perception needed for the central bond and atoms 2 and 3 of a torsion is likely to be different from that needed for terminal atoms and bonds. To start with we will treat them the same, but I want to design in the capability to distinguish them.

Could you elaborate on this? Would love to know what you're thinking here.

**Comment by cbayly13** [comment]
@jchodera @davidlmobley @bannanc : elaborating on why sampling some bonds or atoms differently: my thinking is based on my experience that most of the key science in parameter development rests on speciating a genus of parameter into subtypes, e.g. a torsion genus having a trivalent neutral N single bonded to a trivalent neutral C (SMIRKS '[_:1]~[#7X3+0:2]-[#6X3:3]~[_:4]'), which is certain to have a dominant twofold potential with a modest barrier. Speciation, based only on modifying substituents (including but not limited to atom:1 and atom:4) and bonds to them, is the big question: Is the twofold barrier different enough to warrant differentiation? Will some other-than-twofold terms be needed to nuance the twofold? This is where forcefields establish high or low quality. Changing the central bond or its atoms dramatically changes the potential; it is _almost_ always like resetting the torsion to the beginning of parameterization. So my thinking is to change the central bond or its atoms much less frequently, to favor speciation into subtypes over against jumping into a torsion of a completely different character.

**Comment by jchodera** [comment]
> So my thinking is to change the central bond or its atoms much less frequently, to favor speciation into subtypes over against jumping into a torsion of a completely different character.

This sounds great. We could create a `ProposalEngine` that proposes changes to central atoms or bonds with different probabilities than changes to outer atoms/bonds or proximal atoms/bonds.

Perhaps the `TorsionChemicalEnvironment` could have methods `chooseAtom()` and `chooseBond()` that take optional arguments like `location` that can be one of `['central', 'outer', 'environment']`?

**Comment by cbayly13** [comment]
@jchodera : your ProposalEngine could work; I am mocking up something in branch EnvMoves which is a form of that. Right now I am just trying to embody the chemistry concept (I am becoming conscious that I only have about 3 weeks left).
`['central', 'outer', 'environment']` are good suggestions too.

**Comment by bannanc** [comment]
As of pull request #112 ChemicalEnvironments can determine their types. The method `getType()` returns one of the following:

```
'Bond' # 2 indexed atoms
'Angle' # 3 indexed atoms
'Torsion' # 4 indexed atoms 1~2~3~4
'Improper' # 4 indexed atoms 1~2(~3)~4
'vdW' # 1 indexed atom
None # for 0 indexed atoms or >4 indexed atoms
```

I think specifying location is a generally good idea I'm going to write an issue for chemical environment enhancements that I think are a separate issue from this.
