### ISSUE TITLE
Environment add isValid method

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#96]
I am realizing more and more that we need a check that the generated chemical environment is valid, that is can at least be parse. I think I will use OEchem to check that the generated SMIRKS is parseable.

**Comment by davidlmobley** [comment]
I would do this within the environment objects themselves, as noted in #112 .

**Comment by bannanc** [comment]
Addressing in [openforcefield PR](https://github.com/open-forcefield-group/openforcefield/pull/7)
