### ISSUE TITLE
Next Generation sampler using chemical environments

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#97]
I'm working on generalizing the sampler that we were using for smarty to work with chemical environments. I don't have details to discuss now, but it seemed like there should be an issue for this.

**Comment by bannanc** [comment]
@davidlmobley 
The sampler now exists which was the point of this issue, there are enhancements that I think need their own issues? 
I think we should just close this and write more specific ones for the changes being made.

**Comment by davidlmobley** [comment]
Yes, agreed @bannanc
